/**
 * PLACE automations TEST — sandbox config + safety stubs. George OK 30.09.2026 09:19: TESTS/DRAFTS ONLY.
 *
 * Every module (10-*.gs … 50-*.gs) is generated by build-test-project.sh and runs inside a
 * function wrapper whose PropertiesService / SpreadsheetApp / GmailApp / MailApp / UrlFetchApp /
 * ScriptApp / Logger are the T_* stubs below:
 *   - SpreadsheetApp.openById() only opens the 4 TEST copies; any other id (production!) throws.
 *   - GmailApp.createDraft() does NOT create a draft: it writes «would draft …» to the Log tab.
 *     sendEmail / MailApp / UrlFetchApp (Telegram) / new triggers: throw «TEST GUARD».
 *   - Script Properties are per module (T_PROPS below) + persisted state with prefix T_<MOD>_.
 * Output: tab «Log» in «Place Inbox TEST». George DM: off (no bot token in this project) -> log only.
 * No time triggers. Nothing in this project touches production sheets, the live bridge or TG.
 */
var T_IDS = {
  resident: '1THjNTF1S0Gu3aHeAD4vxK0Ylcf5BDhTqsL2GMaq8cH4', // Resident info TEST (Office rent fixtures, 24/7 columns)
  schedule: '13viAmqT1XMQ99twJw-u5AaTtHWSGPki0zzEX7PleYYg', // Schedule 26 TEST
  events:   '1kkVOqLqVMpwpZtYpshx3zvH5_EGJ7wYp69sKJJQw3Rk', // Events and booking TEST
  inbox:    '1fwjPnLM4JcBH8HnqayWMLdRznU2U7saJX3PQLa9-6GU'  // Place Inbox TEST (Заказы, Issues, Log)
};
var T_PROD_IDS = ['1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4', '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc',
  '1BSwm4sY-ksXjFNEEsAdyiWmUDzgbQlJpL_dh9JIdZAc', '1uMHYp6d-Ji9VQj5xtESiXummBNX9bC8vTruPRQLs8jw'];
var T_LOG_TAB = 'Log';
var T_PROPS = {
  ST6: {RESIDENT_SHEET_ID: T_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
        ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'test-digest@example.invalid', TODAY_OVERRIDE: '2026-09-30'},
  ISS: {ISSUES_MODE: 'live'},  // 'live' here = writes to Issues in Place Inbox TEST only (SHEET_ID = T_IDS.inbox)
  BKG: {EVENTS_SHEET_ID: T_IDS.events, BOOKING_TABS: JSON.stringify(['Meeting room', '1 floor', '4 floor', 'ART Room ', '6 floor'])},
  ST5: {SCHEDULE_SHEET_ID: T_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', ACCOUNTANT_TO: 'test-accountant@example.invalid'},
  KH:  {RESIDENT_SHEET_ID: T_IDS.resident, KEY_TAB: 'Лист1'}
};
var T_RUNNER = 'apps-script';            // the node harness sets 'node-harness'
var T_BUF = [];                            // Logger lines of the current test

function T_now_() { return Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm:ss'); }
function T_log_(item, fn, result, details) {
  var sh = SpreadsheetApp.openById(T_IDS.inbox).getSheetByName(T_LOG_TAB);
  var row = [T_now_(), item, fn, T_RUNNER, String(result), String(details || '').slice(0, 45000)];
  if (sh) sh.appendRow(row); else Logger.log(row.join(' | '));
}
function T_guardId_(id) {
  if (T_PROD_IDS.indexOf(id) >= 0) throw new Error('TEST GUARD: production sheet blocked ' + id);
  var ok = Object.keys(T_IDS).some(function (k) { return T_IDS[k] === id; });
  if (!ok) throw new Error('TEST GUARD: sheet is not in T_IDS ' + id);
}
var T_SS = { openById: function (id) { T_guardId_(id); return SpreadsheetApp.openById(id); } };
function T_props_(mod) {
  var real = PropertiesService.getScriptProperties(), pre = 'T_' + mod + '_';
  var api = {
    getProperty: function (k) { var v = real.getProperty(pre + k); if (v !== null && v !== undefined) return v; var d = (T_PROPS[mod] || {})[k]; return d === undefined ? null : String(d); },
    setProperty: function (k, v) { real.setProperty(pre + k, v); return api; },
    deleteProperty: function (k) { real.deleteProperty(pre + k); return api; }
  };
  return { getScriptProperties: function () { return api; } };
}
var T_GMAIL = {
  createDraft: function (to, subject, body, opts) {
    T_BUF.push('[STUB GmailApp.createDraft — NOT created] to=' + to + (opts && opts.cc ? ' cc=' + opts.cc : '') + '\nSubject: ' + subject + '\n' + body);
    return { getId: function () { return 'TEST-STUB-DRAFT'; } };
  },
  sendEmail: function () { throw new Error('TEST GUARD: GmailApp.sendEmail disabled'); }
};
var T_MAIL = { sendEmail: function () { throw new Error('TEST GUARD: MailApp disabled'); } };
var T_FETCH = { fetch: function (u) { throw new Error('TEST GUARD: UrlFetchApp disabled (no Telegram in TEST): ' + String(u).replace(/bot[^/]+/, 'bot***')); } };
var T_SCRIPT = {
  getProjectTriggers: function () { return []; },
  newTrigger: function () { throw new Error('TEST GUARD: triggers disabled in TEST'); },
  deleteTrigger: function () {}
};
var T_LOGGER = { log: function (x) { T_BUF.push(typeof x === 'string' ? x : JSON.stringify(x)); } };

/** Runs fn, writes result + Logger lines to Log. Never throws (error is logged). */
function T_run_(item, fnName, fn) {
  T_BUF = [];
  var res, status;
  try { res = fn(); status = 'OK'; } catch (e) { res = e && e.message; status = 'ERROR'; }
  var details = (typeof res === 'string' ? res : JSON.stringify(res)) + (T_BUF.length ? '\n--- log ---\n' + T_BUF.join('\n') : '');
  T_log_(item, fnName, status, details);
  return {status: status, result: res, log: T_BUF.slice()};
}
