/**
 * PLACE automations TEST — config, safety layer, relay to George. George OK 30.09.2026 10:02: SCHEDULED TEST MODE.
 *
 * Modules 10-*.gs … 60-*.gs are generated by build-test-project.sh. Each runs inside a function wrapper whose
 * PropertiesService / SpreadsheetApp / GmailApp / MailApp / UrlFetchApp / ScriptApp / Logger are the T_* objects below.
 *
 * SAFETY
 *   - Production sheets (Resident info, Schedule 26, Events and booking, Place Inbox / orders bridge) open READ-ONLY:
 *     every method except get…, is…, has… throws «TEST GUARD». Writes are possible only in the TEST copies (T_IDS),
 *     in practice only Issues + Log in «Place Inbox TEST». Any other spreadsheet id throws.
 *   - NOTHING goes to its real target. GmailApp.createDraft/sendEmail, MailApp and Telegram sendMessage from modules are
 *     intercepted and RELAYED to George's private chat with @PlaceLeadBot as
 *       «🧪 TEST, would be sent to: <recipient> via <channel>, at <time>» + the exact text.
 *     T_relay_ can only send to Script Property GEORGE_CHAT_ID and only if it is a private chat id (positive number).
 *     Without TG_TOKEN or GEORGE_CHAT_ID the relay is LOG ONLY (tab Log).
 *   - The bot token is NEVER in code: set Script Property TG_TOKEN by hand (Project Settings ▸ Script properties).
 *   - The live bridge is not touched. «Тех вопросы» messages are read read-only from the production queue tab.
 * Fixture tests (test_*) use the TEST copies and never relay (log only).
 */
var T_IDS = {  // TEST copies in «PLACE TEST sandbox» (writable)
  resident: '1THjNTF1S0Gu3aHeAD4vxK0Ylcf5BDhTqsL2GMaq8cH4', // Resident info TEST
  schedule: '13viAmqT1XMQ99twJw-u5AaTtHWSGPki0zzEX7PleYYg', // Schedule 26 TEST
  events:   '1kkVOqLqVMpwpZtYpshx3zvH5_EGJ7wYp69sKJJQw3Rk', // Events and booking TEST
  inbox:    '1fwjPnLM4JcBH8HnqayWMLdRznU2U7saJX3PQLa9-6GU'  // Place Inbox TEST (Issues, Log)
};
var P_IDS = {  // PRODUCTION (read-only through T_SS)
  resident: '1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4', // Resident info
  schedule: '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc', // Schedule 26
  events:   '1BSwm4sY-ksXjFNEEsAdyiWmUDzgbQlJpL_dh9JIdZAc', // Events and booking
  inbox:    '1uMHYp6d-Ji9VQj5xtESiXummBNX9bC8vTruPRQLs8jw'  // Place Inbox (orders bridge sheet, tab queue)
};
var T_PROD_IDS = Object.keys(P_IDS).map(function (k) { return P_IDS[k]; });
var T_LOG_TAB = 'Log';
var T_BOOKING_TABS = JSON.stringify(['Meeting room', '1 floor', '4 floor', 'ART Room ', '6 floor']);
/** Known Telegram chats -> human label for the «would be sent to» line. */
var T_CHAT_LABELS = {'-1003641241156': ['PLACE Team', 'TG group PLACE Team'], '626363253': ['Lena', 'TG DM Lena']};

var T_PROFILES = {
  /** fixture = synthetic data in the TEST copies (test_* functions, log only) */
  fixture: {
    ST6: {RESIDENT_SHEET_ID: T_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
          ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'test-digest@example.invalid', TODAY_OVERRIDE: '2026-09-30'},
    ISS: {ISSUES_MODE: 'live'},  // 'live' = writes to Issues in Place Inbox TEST only (SHEET_ID = T_IDS.inbox)
    BKG: {EVENTS_SHEET_ID: T_IDS.events, BOOKING_TABS: T_BOOKING_TABS},
    ST5: {SCHEDULE_SHEET_ID: T_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', ACCOUNTANT_TO: 'test-accountant@example.invalid'},
    KH:  {RESIDENT_SHEET_ID: T_IDS.resident, KEY_TAB: 'Лист1'},
    SC:  {SCHEDULE_SHEET_ID: T_IDS.schedule, EXCLUDE_NAMES: 'Aiz', COVERAGE_MODE: 'draft', DIGEST_TO: 'test-digest@example.invalid'}
  },
  /** sched = scheduled TEST mode: production data read-only, writes only to Place Inbox TEST, every message relayed to George */
  sched: {
    ST6: {RESIDENT_SHEET_ID: P_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
          ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'info@placecoworking.com'},
    ISS: {ISSUES_MODE: 'live'},
    BKG: {EVENTS_SHEET_ID: P_IDS.events, BOOKING_TABS: T_BOOKING_TABS},
    ST5: {SCHEDULE_SHEET_ID: P_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', EXCLUDE_NAMES: '',
          ACCOUNTANT_TO: 'accountant Khun Sirikanya (real address not configured in TEST)'},
    KH:  {RESIDENT_SHEET_ID: P_IDS.resident, KEY_TAB: 'Лист1'},
    SC:  {SCHEDULE_SHEET_ID: P_IDS.schedule, EXCLUDE_NAMES: 'Aiz', COVERAGE_MODE: 'draft', DIGEST_TO: 'info@placecoworking.com'}
  }
};
var T_PROFILE = 'fixture';
var T_CTX = {relay: false, mail: null};   // set per job: relay on/off, mail(to) -> {recipient, channel}
var T_RUNNER = 'apps-script';             // the node harness sets 'node-harness'
var T_BUF = [];                             // Logger lines of the current run

function T_now_() { return Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm:ss'); }
function T_log_(item, fn, result, details) {
  var sh = SpreadsheetApp.openById(T_IDS.inbox).getSheetByName(T_LOG_TAB);
  var row = [T_now_(), item, fn, T_RUNNER + ':' + T_PROFILE, String(result), T_mask_(String(details || '')).slice(0, 45000)];
  if (sh) sh.appendRow(row); else Logger.log(row.join(' | '));
}
function T_mask_(s) { return String(s).replace(/bot\d+:[A-Za-z0-9_-]+/g, 'bot***').replace(/\d{8,10}:[A-Za-z0-9_-]{30,}/g, '***'); }

// ---------- spreadsheets: TEST writable, production read-only ----------
var T_RO_ALLOW = /^(get|is|has|toString$)/;
function T_readOnly_(obj, where) {
  if (obj === null || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(function (x) { return T_readOnly_(x, where); });
  if (obj instanceof Date || Object.prototype.toString.call(obj) === '[object Date]') return obj;  // every other object (Spreadsheet, Sheet, Range, …) is wrapped
  return new Proxy({}, {
    get: function (_, prop) {
      if (typeof prop !== 'string') return undefined;
      if (!T_RO_ALLOW.test(prop)) return function () { throw new Error('TEST GUARD: production is read-only (' + where + '.' + prop + ')'); };
      var f = obj[prop];
      if (typeof f !== 'function') return f;
      return function () { return T_readOnly_(f.apply(obj, arguments), where); };
    },
    set: function () { throw new Error('TEST GUARD: production is read-only (' + where + ')'); }
  });
}
var T_SS = {
  openById: function (id) {
    if (T_PROD_IDS.indexOf(id) >= 0) return T_readOnly_(SpreadsheetApp.openById(id), 'prod:' + id.slice(0, 6));
    var ok = Object.keys(T_IDS).some(function (k) { return T_IDS[k] === id; });
    if (!ok) throw new Error('TEST GUARD: sheet is not in T_IDS/P_IDS ' + id);
    return SpreadsheetApp.openById(id);
  }
};

// ---------- per-module Script Properties ----------
function T_props_(mod) {
  var real = PropertiesService.getScriptProperties(), pre = 'T_' + mod + '_';
  var api = {
    getProperty: function (k) {
      var v = real.getProperty(pre + T_PROFILE + '_' + k); if (v !== null && v !== undefined) return v;
      var d = ((T_PROFILES[T_PROFILE] || {})[mod] || {})[k]; return d === undefined ? null : String(d);
    },
    setProperty: function (k, v) { real.setProperty(pre + T_PROFILE + '_' + k, v); return api; },
    deleteProperty: function (k) { real.deleteProperty(pre + T_PROFILE + '_' + k); return api; }
  };
  return { getScriptProperties: function () { return api; } };
}

// ---------- relay: the ONLY outgoing channel (George's DM) ----------
function T_relay_(recipient, channel, text) {
  var head = '🧪 TEST, would be sent to: ' + recipient + ' via ' + channel + ', at ' + T_now_();
  var full = head + '\n\n' + text;
  if (!T_CTX.relay) { T_BUF.push('[relay off: fixture test]\n' + full); return 'log-only(fixture)'; }
  var p = PropertiesService.getScriptProperties(), tok = p.getProperty('TG_TOKEN'), chat = p.getProperty('GEORGE_CHAT_ID');
  if (!tok || !chat || !/^\d{5,15}$/.test(chat)) {   // private chats only; groups have negative ids
    T_BUF.push('[relay LOG ONLY: ' + (!tok ? 'TG_TOKEN not set' : 'GEORGE_CHAT_ID not set/invalid') + ']\n' + full);
    return 'log-only';
  }
  var parts = [], s = full;
  while (s.length) { parts.push(s.slice(0, 3900)); s = s.slice(3900); }
  var codes = parts.map(function (part, i) {
    var r = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
      payload: JSON.stringify({chat_id: chat, text: (i ? '🧪 (cont.)\n' : '') + part, disable_web_page_preview: true}), muteHttpExceptions: true});
    return r.getResponseCode();
  });
  T_BUF.push('[relayed to George, HTTP ' + codes.join(',') + ']\n' + full);
  return 'relayed:' + codes.join(',');
}
function T_mailTarget_(to) { return T_CTX.mail ? T_CTX.mail(to) : {recipient: to, channel: 'email draft (info@) to ' + to}; }
var T_GMAIL = {
  createDraft: function (to, subject, body, opts) {
    var t = T_mailTarget_(to);
    T_relay_(t.recipient, t.channel, 'Subject: ' + subject + (opts && opts.cc ? '\nCc: ' + opts.cc : '') +
      (opts && opts.attachments ? '\nAttachments: ' + opts.attachments.length : '') + '\n\n' + body);
    return { getId: function () { return 'TEST-RELAYED'; } };
  },
  sendEmail: function (to, subject, body) { var t = T_mailTarget_(to); T_relay_(t.recipient, 'email to ' + to, 'Subject: ' + subject + '\n\n' + body); }
};
var T_MAIL = { sendEmail: function (to, subject, body) { T_GMAIL.sendEmail(to, subject, body); } };
var T_FETCH = {
  fetch: function (u, o) {
    var url = String(u);
    if (/api\.telegram\.org\/bot[^/]+\/sendMessage/.test(url)) {
      var pl = {}; try { pl = JSON.parse((o && o.payload) || '{}'); } catch (e) {}
      var lab = T_CHAT_LABELS[String(pl.chat_id)] || ['chat ' + pl.chat_id, 'TG chat ' + pl.chat_id];
      T_relay_(lab[0], lab[1], String(pl.text || ''));
      return { getResponseCode: function () { return 200; }, getContentText: function () { return '{"ok":true,"test":true}'; } };
    }
    throw new Error('TEST GUARD: UrlFetchApp blocked in modules: ' + T_mask_(url));
  }
};
var T_SCRIPT = {
  getProjectTriggers: function () { return []; },
  newTrigger: function () { throw new Error('TEST GUARD: modules cannot create triggers (use installTestTriggers)'); },
  deleteTrigger: function () {}
};
var T_LOGGER = { log: function (x) { T_BUF.push(typeof x === 'string' ? x : JSON.stringify(x)); } };

/** Runs fn, writes result + Logger lines to Log. Never throws (error is logged). */
function T_run_(item, fnName, fn) {
  T_BUF = [];
  var res, status;
  try { res = fn(); status = 'OK'; } catch (e) { res = e && e.message; status = 'ERROR'; }
  var details = (typeof res === 'string' ? res : JSON.stringify(res)) + (T_BUF.length ? '\n--- log ---\n' + T_BUF.join('\n') : '');
  T_log_(item, fnName, status, details);
  return {status: status, result: res, log: T_BUF.slice()};
}
/** Scheduled job: production read-only, relay on. */
function T_job_(item, fnName, mail, fn) {
  var prev = [T_PROFILE, T_CTX];
  T_PROFILE = 'sched'; T_CTX = {relay: true, mail: mail || null};
  try { return T_run_(item, fnName, fn); } finally { T_PROFILE = prev[0]; T_CTX = prev[1]; }
}
/** Fixture test: TEST copies, relay off. */
function T_fixture_(item, fnName, fn) {
  var prev = [T_PROFILE, T_CTX];
  T_PROFILE = 'fixture'; T_CTX = {relay: false, mail: null};
  try { return T_run_(item, fnName, fn); } finally { T_PROFILE = prev[0]; T_CTX = prev[1]; }
}
