/**
 * PLACE automations TEST — config, safety layer, relay to George + Lena. George OK 30.09.2026 10:02: SCHEDULED TEST MODE.
 *
 * Modules 10-*.gs … 60-*.gs are generated by build-test-project.sh. Each runs inside a function wrapper whose
 * PropertiesService / SpreadsheetApp / GmailApp / MailApp / UrlFetchApp / ScriptApp / Logger are the T_* objects below.
 *
 * SAFETY
 *   - Production sheets (Resident info, Schedule 26, Events and booking, Place Inbox / orders bridge) open READ-ONLY:
 *     every method except get…, is…, has… throws «TEST GUARD». Writes are possible only in the TEST copies (T_IDS),
 *     in practice only Issues + Log in «Place Inbox TEST». Any other spreadsheet id throws.
 *   - SINCE 03.10.2026 09:17 (George): scheduled jobs go to the REAL recipients with a «[TEST] » prefix — see T_REAL /
 *     T_realTarget_ below (PLACE Team, «Тех вопросы», Payments Place, Lena). Script Property T_ROUTING=relay restores the old mode:
 *   - (old mode) NOTHING goes to its real target. GmailApp.createDraft/sendEmail, MailApp and Telegram sendMessage from modules are
 *     intercepted and RELAYED (George's instruction 30.09 14:22) to BOTH George and Lena in their private chats with
 *     @PlaceLeadBot (Script Properties GEORGE_CHAT_ID and LENA_CHAT_ID) as:
 *       🧪 ТЕСТ · Куда ушло бы: <real recipient, short>
 *       <blank line>
 *       <the exact original text>
 *     Only private chat ids (positive numbers) are used. LENA_CHAT_ID empty → George only + a warning in Log.
 *     GEORGE_CHAT_ID empty → Lena only + warning. Both empty or no TG_TOKEN → LOG ONLY (tab Log). Never fails the job.
 *   - The bot token is NEVER in code: set Script Property TG_TOKEN by hand (Project Settings ▸ Script properties).
 *   - The live bridge is not touched. «Тех вопросы» messages are read read-only from the production queue tab.
 * Fixture tests (test_*) use the TEST copies and never relay (log only).
 */
var T_IDS = {  // TEST copies in «PLACE TEST sandbox» (writable)
  resident: '1THjNTF1S0Gu3aHeAD4vxK0Ylcf5BDhTqsL2GMaq8cH4', // Resident info TEST
  schedule: '13viAmqT1XMQ99twJw-u5AaTtHWSGPki0zzEX7PleYYg', // Schedule 26 TEST
  events:   '1kkVOqLqVMpwpZtYpshx3zvH5_EGJ7wYp69sKJJQw3Rk', // Events and booking TEST
  inbox:    '1fwjPnLM4JcBH8HnqayWMLdRznU2U7saJX3PQLa9-6GU'  // Place Inbox TEST (Issues, Log)
};
var P_IDS = {  // PRODUCTION (read-only through T_SS)
  resident: '1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4', // Resident info
  schedule: '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc', // Schedule 26
  events:   '1BSwm4sY-ksXjFNEEsAdyiWmUDzgbQlJpL_dh9JIdZAc', // Events and booking
  inbox:    '1uMHYp6d-Ji9VQj5xtESiXummBNX9bC8vTruPRQLs8jw'  // Place Inbox (orders bridge sheet, tab queue)
};
var T_PROD_IDS = Object.keys(P_IDS).map(function (k) { return P_IDS[k]; });
var T_LOG_TAB = 'Log';
var T_BOOKING_TABS = JSON.stringify(['Meeting room', '1 floor', '4 floor', 'ART Room ', '6 floor']);
/** Known Telegram chats -> human label for the «would be sent to» line. */
/** Known production Telegram chats -> «Куда ушло бы» label (used when a module calls sendMessage itself). */
var T_CHAT_LABELS = {'-1003641241156': 'PLACE Team', '626363253': 'Лена (ЛС)'};

var T_PROFILES = {
  /** fixture = synthetic data in the TEST copies (test_* functions, log only) */
  fixture: {
    ST6: {RESIDENT_SHEET_ID: T_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
          ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'test-digest@example.invalid', TODAY_OVERRIDE: '2026-09-30'},
    ISS: {ISSUES_MODE: 'live'},  // 'live' = writes to Issues in Place Inbox TEST only (SHEET_ID = T_IDS.inbox)
    BKG: {EVENTS_SHEET_ID: T_IDS.events, BOOKING_TABS: T_BOOKING_TABS},
    ST5: {SCHEDULE_SHEET_ID: T_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', ACCOUNTANT_TO: 'test-accountant@example.invalid'},
    KH:  {RESIDENT_SHEET_ID: T_IDS.resident, KEY_TAB: 'Лист1'},
    SC:  {SCHEDULE_SHEET_ID: T_IDS.schedule, EXCLUDE_NAMES: 'Aiz', COVERAGE_MODE: 'draft', DIGEST_TO: 'test-digest@example.invalid'},
    LV:  {LEAVE_SHEET_ID: T_IDS.inbox, SCHEDULE_SHEET_ID: T_IDS.schedule, LEAVE_APPROVER: 'George'}  // writes: Leave tab + Schedule 26 TEST
  },
  /** sched = scheduled TEST mode: production data read-only, writes only to Place Inbox TEST, every message relayed to George */
  sched: {
    ST6: {RESIDENT_SHEET_ID: P_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
          ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'info@placecoworking.com'},
    ISS: {ISSUES_MODE: 'live'},
    BKG: {EVENTS_SHEET_ID: P_IDS.events, BOOKING_TABS: T_BOOKING_TABS},
    ST5: {SCHEDULE_SHEET_ID: P_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', EXCLUDE_NAMES: '',
          ACCOUNTANT_TO: 'new accountant Pat (address not known yet; not configured in TEST)'},
    KH:  {RESIDENT_SHEET_ID: P_IDS.resident, KEY_TAB: 'Лист1'},
    SC:  {SCHEDULE_SHEET_ID: P_IDS.schedule, EXCLUDE_NAMES: 'Aiz', COVERAGE_MODE: 'draft', DIGEST_TO: 'info@placecoworking.com'},
    LV:  {LEAVE_SHEET_ID: T_IDS.inbox, SCHEDULE_SHEET_ID: T_IDS.schedule, LEAVE_APPROVER: 'George'}  // staged: TEST copies only, never production
  }
};
var T_PROFILE = 'fixture';
var T_CTX = {relay: false, mail: null};   // per job: relay on/off; mail(to) -> «Куда ушло бы» label; self-test only: ids {george, lena}, send(id, text)
var T_RUNNER = 'apps-script';             // the node harness sets 'node-harness'
var T_BUF = [];                             // Logger lines of the current run

/** Read by issues-log.gs / stage6 when they append Issues rows: rows written by fixture tests are tagged 'fixture'
 *  (skipped by the team digests and job_stage6, deleted by cleanupTestFixtures / test_all). */
function ISSUES_TAG_FN() { return T_PROFILE === 'fixture' ? 'fixture' : ''; }

function T_now_() { return Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm:ss'); }
function T_log_(item, fn, result, details) {
  var sh = SpreadsheetApp.openById(T_IDS.inbox).getSheetByName(T_LOG_TAB);
  var row = [T_now_(), item, fn, T_RUNNER + ':' + T_PROFILE, String(result), T_mask_(String(details || '')).slice(0, 45000)];
  if (sh) sh.appendRow(row); else Logger.log(row.join(' | '));
}
function T_mask_(s) { return String(s).replace(/bot\d+:[A-Za-z0-9_-]+/g, 'bot***').replace(/\d{8,10}:[A-Za-z0-9_-]{30,}/g, '***'); }

// ---------- spreadsheets: TEST writable, production read-only ----------
var T_RO_ALLOW = /^(get|is|has|toString$)/;
function T_readOnly_(obj, where) {
  if (obj === null || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(function (x) { return T_readOnly_(x, where); });
  if (obj instanceof Date || Object.prototype.toString.call(obj) === '[object Date]') return obj;  // every other object (Spreadsheet, Sheet, Range, …) is wrapped
  return new Proxy({}, {
    get: function (_, prop) {
      if (typeof prop !== 'string') return undefined;
      if (!T_RO_ALLOW.test(prop)) return function () { throw new Error('TEST GUARD: production is read-only (' + where + '.' + prop + ')'); };
      var f = obj[prop];
      if (typeof f !== 'function') return f;
      return function () { return T_readOnly_(f.apply(obj, arguments), where); };
    },
    set: function () { throw new Error('TEST GUARD: production is read-only (' + where + ')'); }
  });
}
var T_SS = {
  openById: function (id) {
    if (T_PROD_IDS.indexOf(id) >= 0) return T_readOnly_(SpreadsheetApp.openById(id), 'prod:' + id.slice(0, 6));
    var ok = Object.keys(T_IDS).some(function (k) { return T_IDS[k] === id; });
    if (!ok) throw new Error('TEST GUARD: sheet is not in T_IDS/P_IDS ' + id);
    return SpreadsheetApp.openById(id);
  }
};

// ---------- per-module Script Properties ----------
/** Script Properties shared by all modules, read unprefixed. TECH_CHAT_ID = «Тех вопросы» group (real target of the
 *  issues digests, unknown yet → empty). */
var T_SHARED_PROPS = ['TECH_CHAT_ID', 'PAY_CHAT_ID'];   // PAY_CHAT_ID = payment-reminders group (George is adding the bot; empty for now)
function T_props_(mod) {
  var real = PropertiesService.getScriptProperties(), pre = 'T_' + mod + '_';
  var api = {
    getProperty: function (k) {
      if (T_CTX.props && k in T_CTX.props) return T_CTX.props[k];            // self-tests only
      if (k === 'TOKEN') return 'TEST-NO-TOKEN';                              // modules never see the real bot token (fetch is intercepted)
      if (T_SHARED_PROPS.indexOf(k) >= 0) return real.getProperty(k);         // shared, unprefixed (set by hand)
      var v = real.getProperty(pre + T_PROFILE + '_' + k); if (v !== null && v !== undefined) return v;
      var d = ((T_PROFILES[T_PROFILE] || {})[mod] || {})[k]; return d === undefined ? null : String(d);
    },
    setProperty: function (k, v) { real.setProperty(pre + T_PROFILE + '_' + k, v); return api; },
    deleteProperty: function (k) { real.deleteProperty(pre + T_PROFILE + '_' + k); return api; }
  };
  return { getScriptProperties: function () { return api; } };
}

// ---------- relay: the ONLY outgoing channel (private chats of George + Lena) ----------
/** Test message text: header, «Куда ушло бы», blank line, original body. */
/** One short header line (George 01.10: «кратко»): «🧪 ТЕСТ · Куда ушло бы: <where>», blank line, original text. */
/** where = null → only the short «🧪 ТЕСТ · » marker (issues digests, George 01.10 23:10). */
function T_relayText_(where, text) {
  var body = String(text == null ? '' : text);
  return where ? '🧪 ТЕСТ · Куда ушло бы: ' + where + '\n\n' + body : '🧪 ТЕСТ · ' + body;
}
/** Relay targets from Script Properties (or T_CTX.ids in the self-test). Returns {ids: [{who, id}], warnings: []}. */
function T_relayTargets_() {
  var ids = T_CTX.ids, warn = [], out = [];
  if (!ids) { var p = PropertiesService.getScriptProperties(); ids = {george: p.getProperty('GEORGE_CHAT_ID'), lena: p.getProperty('LENA_CHAT_ID')}; }
  var g = String(ids.george || '').trim(), l = String(ids.lena || '').trim(), ok = function (x) { return /^\d{5,15}$/.test(x); };
  if (ok(g)) out.push({who: 'George', id: g}); else warn.push('WARN GEORGE_CHAT_ID ' + (g ? 'invalid (not a private chat id)' : 'not set') + ' → not sent to George');
  if (ok(l) && l !== g) out.push({who: 'Lena', id: l}); else if (!ok(l)) warn.push('WARN LENA_CHAT_ID ' + (l ? 'invalid (not a private chat id)' : 'not set') + ' → sent to George only');
  return {ids: out, warnings: warn};
}
/** Default sender: Telegram sendMessage with the TG_TOKEN Script Property. T_CTX.send replaces it in the self-test. */
function T_tgSend_(chatId, text) {
  var tok = PropertiesService.getScriptProperties().getProperty('TG_TOKEN');
  if (!tok) return 'no-token';
  var r = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
    payload: JSON.stringify({chat_id: chatId, text: text, disable_web_page_preview: true}), muteHttpExceptions: true});
  return r.getResponseCode();
}
// ---------- REAL routing (George 03.10.2026 09:17): TEST jobs go to the real recipients, every message starts with [TEST] ----------
/** Real chats (not secrets). Script Properties TECH_CHAT_ID / PAY_CHAT_ID / LENA_CHAT_ID / TEAM_CHAT_ID / SAK_CHAT_ID override.
 *  Admins have no private chats with @PlaceLeadBot (only the shared @place_coworking_admin), so admin messages go to PLACE Team.
 *  Alena (fired 02.10) is not a recipient. Tenants and the accountant get nothing: office/e-mail/timesheet items go to Lena. */
var T_REAL = {team: '-1003641241156', tech: '-5341674959', pay: '-1003702681187', lena: '626363253', sak: ''};
/** Script Property T_ROUTING: 'real' (default since 03.10) | 'relay' (old mode: George + Lena DMs with «Куда ушло бы»). */
function T_routing_() { return String(PropertiesService.getScriptProperties().getProperty('T_ROUTING') || 'real').toLowerCase(); }
function T_realId_(k) {
  var map = {team: 'TEAM_CHAT_ID', tech: 'TECH_CHAT_ID', pay: 'PAY_CHAT_ID', lena: 'LENA_CHAT_ID', sak: 'SAK_CHAT_ID'};
  return String(PropertiesService.getScriptProperties().getProperty(map[k]) || T_REAL[k] || '').trim();
}
/** «where» label → {key, name, pre} | null (= not a real send: use the old George + Lena relay, e.g. the ping). */
function T_realTarget_(where) {
  var w = where == null ? '' : String(where);
  if (!w) return {key: 'tech', name: 'Тех вопросы'};                                   // issues digests (label-less)
  if (/никуда|проверка связи/i.test(w)) return null;                                   // sendTestPing
  if (/PLACE Team/i.test(w)) return {key: 'team', name: 'PLACE Team'};
  if (/вечерний админ/i.test(w)) {
    var m = w.match(/вечерний админ\s+([^()→]+?)\s*\(ЛС\)/i);
    return {key: 'team', name: 'PLACE Team (вечерний админ)', pre: m ? 'Вечерний админ: ' + m[1].trim() + '\n' : ''};
  }
  if (/PAY_CHAT_ID|Payments/i.test(w)) return {key: 'pay', name: 'Payments Place'};
  if (/Тех вопросы/i.test(w)) return {key: 'tech', name: 'Тех вопросы'};
  if (/Сак/i.test(w)) return {key: 'sak', name: 'Сак (ЛС)'};
  return {key: 'lena', name: 'Лена (ЛС)', pre: /email|черновик|арендатор|Pat/i.test(w) ? 'Для: ' + w + '\n' : ''};   // offices, coverage, timesheet, leave
}
/** Real send: «[TEST] » + text to the real chat. Empty chat id / no TG_TOKEN → log only. */
function T_sendReal_(t, text) {
  var id = T_realId_(t.key), body = '[TEST] ' + (t.pre || '') + String(text == null ? '' : text);
  if (!id) { T_BUF.push('[real: ' + t.name + ' chat id not set → NOT sent]\n' + body); return 'not-sent(no chat id)'; }
  if (!PropertiesService.getScriptProperties().getProperty('TG_TOKEN')) { T_BUF.push('[real LOG ONLY: TG_TOKEN not set] → ' + t.name + '\n' + body); return 'log-only'; }
  var parts = [], s = body; while (s.length) { parts.push(s.slice(0, 3900)); s = s.slice(3900); }
  var codes = parts.map(function (part, i) { try { return T_tgSend_(id, (i ? '[TEST] (продолжение)\n' : '') + part); } catch (e) { return 'ERR ' + (e && e.message); } });
  T_BUF.push('[sent → ' + t.name + ' ' + id + ': ' + codes.join(',') + ']\n' + body);
  return 'sent ' + t.name + ':' + codes.join(',');
}

/** where = the real recipient + channel in plain Russian, e.g. «PLACE Team (TG группа)», «Лена в личку». */
function T_relay_(where, text) {
  if (T_CTX.relay && !T_CTX.send && T_routing_() === 'real') { var rt = T_realTarget_(where); if (rt) return T_sendReal_(rt, text); }
  var full = T_relayText_(where, text);
  if (!T_CTX.relay) { T_BUF.push('[relay off: fixture test]\n' + full); return 'log-only(fixture)'; }
  var send = T_CTX.send || T_tgSend_;
  if (!T_CTX.send && !PropertiesService.getScriptProperties().getProperty('TG_TOKEN')) {
    T_BUF.push('[relay LOG ONLY: TG_TOKEN not set]\n' + full); return 'log-only';
  }
  var t = T_relayTargets_();
  t.warnings.forEach(function (w) { T_BUF.push(w); });
  if (!t.ids.length) { T_BUF.push('[relay LOG ONLY: no GEORGE_CHAT_ID / LENA_CHAT_ID]\n' + full); return 'log-only'; }
  var parts = [], s = full;   // Telegram limit 4096
  while (s.length) { parts.push(s.slice(0, 3900)); s = s.slice(3900); }
  var res = t.ids.map(function (x) {
    var codes = parts.map(function (part, i) {
      try { return send(x.id, (i ? '🧪 ТЕСТ (продолжение)\n' : '') + part); } catch (e) { return 'ERR ' + (e && e.message); }
    });
    return x.who + ':' + codes.join(',');
  });
  T_BUF.push('[relayed to ' + res.join(' ') + ']\n' + full);
  return 'relayed ' + res.join(' ');
}
/** T_CTX.mail(to) returns the «Куда ушло бы» label for an email/draft; default: «email <to> (черновик на info@)». */
function T_mailTarget_(to) { return T_CTX.mail ? T_CTX.mail(to) : to + ' (email-черновик)'; }
var T_GMAIL = {
  createDraft: function (to, subject, body, opts) {
    T_relay_(T_mailTarget_(to), 'Тема: ' + subject + (opts && opts.attachments ? ' · вложение: ' + opts.attachments.length : '') + '\n' + body);
    return { getId: function () { return 'TEST-RELAYED'; } };
  },
  sendEmail: function (to, subject, body) { T_relay_(T_mailTarget_(to).replace(/\(черновик[^)]*\)/, '(письмо)'), 'Тема: ' + subject + '\n' + body); }
};
var T_MAIL = { sendEmail: function (to, subject, body) { T_GMAIL.sendEmail(to, subject, body); } };
var T_FETCH = {
  fetch: function (u, o) {
    var url = String(u);
    if (/api\.telegram\.org\/bot[^/]+\/sendMessage/.test(url)) {
      var pl = {}; try { pl = JSON.parse((o && o.payload) || '{}'); } catch (e) {}
      var tech = String(T_props_('ISS').getScriptProperties().getProperty('TECH_CHAT_ID') || '');
      T_relay_(tech && String(pl.chat_id) === tech ? null : (T_CHAT_LABELS[String(pl.chat_id)] || ('TG чат ' + pl.chat_id)), String(pl.text || ''));
      return { getResponseCode: function () { return 200; }, getContentText: function () { return '{"ok":true,"test":true}'; } };
    }
    throw new Error('TEST GUARD: UrlFetchApp blocked in modules: ' + T_mask_(url));
  }
};
var T_SCRIPT = {
  getProjectTriggers: function () { return []; },
  newTrigger: function () { throw new Error('TEST GUARD: modules cannot create triggers (use installTestTriggers)'); },
  deleteTrigger: function () {}
};
var T_LOGGER = { log: function (x) { T_BUF.push(typeof x === 'string' ? x : JSON.stringify(x)); } };

/** Runs fn, writes result + Logger lines to Log. Never throws (error is logged). */
function T_run_(item, fnName, fn) {
  T_BUF = [];
  var res, status;
  try { res = fn(); status = 'OK'; } catch (e) { res = e && e.message; status = 'ERROR'; }
  var details = (typeof res === 'string' ? res : JSON.stringify(res)) + (T_BUF.length ? '\n--- log ---\n' + T_BUF.join('\n') : '');
  T_log_(item, fnName, status, details);
  return {status: status, result: res, log: T_BUF.slice()};
}
/** Scheduled job: production read-only, relay on. */
function T_job_(item, fnName, mail, fn) {
  var prev = [T_PROFILE, T_CTX];
  T_PROFILE = 'sched'; T_CTX = {relay: true, mail: mail || null};
  try { return T_run_(item, fnName, fn); } finally { T_PROFILE = prev[0]; T_CTX = prev[1]; }
}
/** Fixture test: TEST copies, relay off. */
function T_fixture_(item, fnName, fn) {
  var prev = [T_PROFILE, T_CTX];
  T_PROFILE = 'fixture'; T_CTX = {relay: false, mail: null};
  try { return T_run_(item, fnName, fn); } finally { T_PROFILE = prev[0]; T_CTX = prev[1]; }
}
