/** GENERATED by build-test-project.sh from issues-log.gs — do not edit here. Module ISS (TEST sandbox). */
var ISS = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {
var SHEET_ID = T_IDS.inbox; // TEST: Place Inbox TEST, never the live bridge sheet
/**
 * Place Coworking — 2.1.5 / 10.1 Breakdown & issue log. DRAFT TEMPLATE, NOT DEPLOYED.
 *
 * Plugs into the TG bridge (docs/ops/tg-bridge/Code.template.gs). Every new
 * top-level message in the «Тех вопросы» chat becomes a row in tab «Issues»
 * (same Place Inbox spreadsheet as «Заказы»). A reply to that message with a
 * "done" word (готово / починил / fixed / เสร็จ / แก้แล้ว / ซ่อมแล้ว …) closes it;
 * any other reply marks it in_progress and is kept as the last note.
 * issuesDigest_() builds the text for the existing 10:07 (open list) and
 * 23:10 (closed today + still open) runs. No new Lead runs, no TG sends here.
 *
 * Hook (one line in poll(), after the orders hook):
 *   if (ISSUES_CHAT_RE.test(chat) && !(u.edited_message)) try { issuesHandle_(issuesSheet_(), m, text, name); } catch (e) { Logger.log('ISSUES_ERR ' + e); }
 *
 * SAFETY: ISSUES_MODE (Script Property) defaults to 'dry' = log only, no sheet
 * writes. 'live' writes to the «Issues» tab — only after George OK.
 */

var ISSUES_CHAT_RE = /тех\s*вопрос/i;
var ISSUES_TAB = 'Issues';
// type: 'issue' = breakdown (default, also for old rows without type) | 'task' = work item (e.g. electricity bill, id 'elec:…').
// tag: '' = real | 'fixture' = written by a test (skipped by digests; test_all deletes them).
var ISSUES_HEAD = ['issue_id', 'opened_at_ict', 'floor', 'reporter', 'text', 'status', 'last_note', 'last_update_ict', 'closed_at_ict', 'closed_by', 'tg_chat_id', 'tg_message_id', 'assignee', 'type', 'tag'];
/** Tag for new rows. The TEST project defines a global ISSUES_TAG_FN() that returns 'fixture' inside test_*; production: ''. */
function issuesTag_() { return typeof ISSUES_TAG_FN === 'function' ? String(ISSUES_TAG_FN() || '') : ''; }
var DONE_RE = /(готово|сделано|сделал|починил|починили|исправил|решено|закрыто|fixed|done|resolved|เสร็จ|แก้แล้ว|ซ่อมแล้ว|เรียบร้อย)/i;
var BOT_RE = /placeleadbot/i;

function issuesSheet_() {
  var ss = SpreadsheetApp.openById(SHEET_ID);
  var sh = ss.getSheetByName(ISSUES_TAB);
  if (!sh) {
    if (issuesMode_() !== 'live') return null;
    sh = ss.insertSheet(ISSUES_TAB);
    sh.appendRow(ISSUES_HEAD);
  }
  return sh;
}

function issuesMode_() { return PropertiesService.getScriptProperties().getProperty('ISSUES_MODE') || 'dry'; }

function issuesHandle_(sh, m, text, sender) {
  var f = m.from || {};
  if (BOT_RE.test(f.username || '')) return 'skip-bot';
  var when = Utilities.formatDate(new Date(m.date * 1000), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm');
  var live = issuesMode_() === 'live' && sh;
  var rows = sh ? sh.getDataRange().getValues() : [ISSUES_HEAD];
  var col = {}; ISSUES_HEAD.forEach(function (h, i) { col[h] = i; });
  var replyTo = m.reply_to_message ? String(m.reply_to_message.message_id) : null;
  if (replyTo) {
    for (var r = 1; r < rows.length; r++) {
      if (String(rows[r][col.tg_message_id]) === replyTo && String(rows[r][col.tg_chat_id]) === String(m.chat.id)) {
        var row = rows[r].slice();
        row[col.last_note] = (sender + ': ' + text).slice(0, 500);
        row[col.last_update_ict] = when;
        if (DONE_RE.test(text)) { row[col.status] = 'closed'; row[col.closed_at_ict] = when; row[col.closed_by] = sender; }
        else if (row[col.status] === 'open') row[col.status] = 'in_progress';
        if (live) sh.getRange(r + 1, 1, 1, ISSUES_HEAD.length).setValues([row]);
        else Logger.log('[issues dry] update row ' + (r + 1) + ': ' + JSON.stringify(row));
        return row[col.status];
      }
    }
    return 'reply-untracked';
  }
  var floor = typeof parseFloor_ === 'function' ? parseFloor_(text) : issuesFloor_(text);
  var newRow = [m.chat.id + ':' + m.message_id, when, floor, sender, text.slice(0, 1000), 'open', '', when, '', '', String(m.chat.id), String(m.message_id), '', 'issue', issuesTag_()];
  if (live) sh.appendRow(newRow); else Logger.log('[issues dry] new: ' + JSON.stringify(newRow));
  return 'open';
}

function issuesFloor_(text) {
  var m = String(text).match(/(\d)\s*(?:этаж|эт\.?|floor|fl\.?|ชั้น)|(?:этаж|floor|ชั้น)\s*(\d)/i);
  return m ? (m[1] || m[2]) : '';
}

/** Type of a row: explicit column, else 'task' for generated ids (elec:…), else 'issue'. */
function issuesType_(x, col) {
  var t = String(x[col.type] || '').trim().toLowerCase();
  if (t) return t;
  return /^elec:/.test(String(x[col.issue_id])) ? 'task' : 'issue';
}
/** One-line, trimmed, max n characters (cut on a word, emoji-safe), with «…». */
function issuesShort_(s, n) {
  var t = String(s == null ? '' : s).replace(/\s+/g, ' ').trim(), a = Array.from ? Array.from(t) : t.split('');
  if (a.length <= n) return t;
  var cut = a.slice(0, n).join(''), sp = cut.lastIndexOf(' ');
  return (sp > n * 0.6 ? cut.slice(0, sp) : cut).replace(/[\s,.;:–—-]+$/, '') + '…';
}
function issuesWhen_(v) {   // 'yyyy-MM-dd HH:mm' or Date -> 'dd.MM HH:mm'
  if (v instanceof Date) return Utilities.formatDate(v, 'Asia/Bangkok', 'dd.MM HH:mm');
  var m = String(v || '').match(/^(\d{4})-(\d\d)-(\d\d)(?:[ T](\d\d:\d\d))?/);
  return m ? m[3] + '.' + m[2] + (m[4] ? ' ' + m[4] : '') : String(v || '');
}
function issuesMs_(v) {
  if (v instanceof Date) return v.getTime();
  var t = new Date(String(v).replace(' ', 'T') + ':00+07:00').getTime();
  return isNaN(t) ? null : t;
}

/** kind: 'morning' (10:07) | 'evening' (23:10). Text for the PLACE Team summary.
 *  Only real breakdowns (type=issue, tag!=fixture). Tasks (electricity bills …) stay in the Issues log only.
 *  opts.includeFixtures = true only for tests. */
function issuesDigest_(kind, now, opts) {
  opts = opts || {};
  var sh = SpreadsheetApp.openById(SHEET_ID).getSheetByName(ISSUES_TAB);
  if (!sh) return 'Issues: вкладки нет (ещё не запущено).';
  var rows = sh.getDataRange().getValues(), col = {}; ISSUES_HEAD.forEach(function (h, i) { col[h] = i; });
  now = now || new Date();
  var today = Utilities.formatDate(now, 'Asia/Bangkok', 'yyyy-MM-dd'), nowMs = now.getTime();
  var open = [], closedToday = [];
  for (var r = 1; r < rows.length; r++) {
    var x = rows[r];
    if (!String(x[col.issue_id] || '').trim() && !String(x[col.text] || '').trim()) continue;   // empty row
    if (issuesType_(x, col) !== 'issue') continue;                                             // tasks: Issues log only
    if (!opts.includeFixtures && String(x[col.tag] || '') === 'fixture') continue;             // test rows
    var what = issuesShort_(x[col.text], 50); if (!what) continue;
    var where = x[col.floor] ? x[col.floor] + ' эт. ' : '';
    var st = String(x[col.status] || 'open');
    if (st === 'closed') {
      var c = x[col.closed_at_ict], cDay = c instanceof Date ? Utilities.formatDate(c, 'Asia/Bangkok', 'yyyy-MM-dd') : String(c);
      if (cDay.indexOf(today) === 0) closedToday.push('✅ ' + where + what);
      continue;
    }
    var ms = issuesMs_(x[col.opened_at_ict]), days = ms === null ? 0 : Math.max(0, Math.floor((nowMs - ms) / 86400000));
    var taken = st === 'in_progress';
    open.push({taken: taken ? 1 : 0, ms: ms || 0,
      s: (taken ? '🟡 ' : '🔴 ') + where + what + ' — ' + (days ? days + ' дн.' : 'сегодня') + (taken ? ', в работе' : '')});
  }
  // short (George 01.10: «кратко»): count, one line per issue (where, what, age), closed today only in the evening
  open.sort(function (a, b) { return a.taken - b.taken || a.ms - b.ms; });
  var out = [open.length ? '🛠 Поломки: ' + open.length : '🛠 Поломок нет'];
  open.forEach(function (o) { out.push(o.s); });
  if (kind === 'evening' && closedToday.length) closedToday.forEach(function (c) { out.push(c); });
  return out.join('\n').replace(/\s+$/, '');
}

/** Sends the digest to the Telegram group «Тех вопросы» (George 30.09 14:27: NOT PLACE Team).
 *  Script Property TECH_CHAT_ID = chat id of «Тех вопросы» (negative, group). Empty → WARN in Logger, nothing is sent.
 *  Bot token: Script Property TOKEN (same as the bridge). */
function issuesSendDigest_(kind, now) {
  var p = PropertiesService.getScriptProperties(), chat = String(p.getProperty('TECH_CHAT_ID') || '').trim();
  var text = issuesDigest_(kind, now);
  if (!chat) { Logger.log('WARN TECH_CHAT_ID not set → issues digest (' + kind + ') NOT sent'); return {sent: false, warning: 'TECH_CHAT_ID not set', text: text}; }
  var tok = p.getProperty('TOKEN');
  if (!tok) { Logger.log('WARN TOKEN not set → issues digest (' + kind + ') NOT sent'); return {sent: false, warning: 'TOKEN not set', text: text}; }
  var r = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
    payload: JSON.stringify({chat_id: chat, text: text, disable_web_page_preview: true}), muteHttpExceptions: true});
  return {sent: r.getResponseCode() === 200, code: r.getResponseCode(), text: text};
}

/** Offline test with fake updates. In dry mode only logs. */
function dryRunIssues() {
  var chat = {id: -100123, title: 'Тех вопросы', type: 'supergroup'}, t = 1790700000;
  var log = [];
  log.push(issuesHandle_(null, {chat: chat, message_id: 501, date: t, from: {username: 'som'}}, 'Кондиционер на 3 этаже течёт', 'Som'));
  log.push(issuesHandle_(null, {chat: chat, message_id: 502, date: t + 60, from: {username: 'tangmo'}}, 'ชั้น 1 ไฟดับ 2 ดวง', 'Tangmo'));
  Logger.log(JSON.stringify(log));
  return log;
}

return {issuesSheet_: issuesSheet_, issuesHandle_: issuesHandle_, issuesDigest_: issuesDigest_, issuesSendDigest_: issuesSendDigest_, ISSUES_CHAT_RE: ISSUES_CHAT_RE};
})(T_props_('ISS'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);
