/** GENERATED by build-test-project.sh from bookings-today.gs — do not edit here. Module BKG (TEST sandbox). */
var BKG = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — G-5 «Брони на сегодня» из Events and booking. DRAFT TEMPLATE, NOT DEPLOYED.
 * READ-ONLY: never writes to the sheet, never sends. Returns text for the existing 10:07 run.
 *
 * Sheet layout (checked read-only 29.09.2026): each tab = one space; row 4 = "Time" + one column
 * per day ("Mon 28/10" or "ПН 11.03"), month marker columns like "Jan\n2025" / "September\n2026"
 * give the year; column A = time slots (09:00, 09:30 …); a booking = any non-empty cell.
 * FINDING 29.09: the «Meeting room» grid ends at Wed 30/09/2026 (+ an "October 2026" marker) —
 * no columns for October yet.
 *
 * Script Properties (optional): EVENTS_SHEET_ID, BOOKING_TABS (JSON list), HEADER_ROW=4, LOOKAHEAD_DAYS=14
 */
var BK_TZ = 'Asia/Bangkok';
var BK_ID = '1BSwm4sY-ksXjFNEEsAdyiWmUDzgbQlJpL_dh9JIdZAc';
var BK_TABS = ['Meeting room', '1 floor', '4 floor', 'ART Room ', 'Workshop room', 'Office room-4 (GREEN)', '6 floor'];
var BK_MONTHS = {jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11};

function dryRunBookings() { var t = bookingsToday_(new Date()); Logger.log(t); return t; }

function bookingsToday_(now) {
  var p = PropertiesService.getScriptProperties();
  var ss = SpreadsheetApp.openById(p.getProperty('EVENTS_SHEET_ID') || BK_ID);
  var tabs = JSON.parse(p.getProperty('BOOKING_TABS') || JSON.stringify(BK_TABS));
  var hr = Number(p.getProperty('HEADER_ROW') || 4), look = Number(p.getProperty('LOOKAHEAD_DAYS') || 14);
  var s = Utilities.formatDate(now, BK_TZ, 'yyyy-MM-dd').split('-');
  var today = new Date(+s[0], +s[1] - 1, +s[2]);
  var horizon = new Date(today.getFullYear(), today.getMonth(), today.getDate() + look);
  var lines = [], warn = [];
  tabs.forEach(function (name) {
    var sh = ss.getSheetByName(name);
    if (!sh) { warn.push('нет вкладки ' + name); return; }
    var disp = sh.getDataRange().getDisplayValues();
    if (disp.length < hr) return;
    var cols = bkDateCols_(disp[hr - 1], today.getFullYear());
    var key = bkKey_(today), col = cols.map[key];
    if (cols.last && cols.last < horizon) warn.push(name.trim() + ': сетка заканчивается ' + Utilities.formatDate(cols.last, BK_TZ, 'dd.MM.yyyy') + ', дальше брони некуда записать');
    if (col === undefined) return;
    var items = [];
    for (var r = hr; r < disp.length; r++) {
      var v = String(disp[r][col] || '').trim();
      if (v) items.push((String(disp[r][0] || '').trim() || '?') + ' ' + v.replace(/\s+/g, ' ').slice(0, 120));
    }
    if (items.length) lines.push('• ' + name.trim() + ':\n   ' + items.join('\n   '));
  });
  return 'Брони на сегодня (' + Utilities.formatDate(today, BK_TZ, 'dd.MM') + '):\n' + (lines.length ? lines.join('\n') : 'нет') +
    (warn.length ? '\n⚠️ ' + warn.join('\n⚠️ ') : '');
}

/** Header row -> {map: {yyyy-mm-dd: colIndex}, last: Date}. Year from month markers; rollover Dec->Jan. */
function bkDateCols_(row, fallbackYear) {
  var map = {}, year = null, lastMonth = null, last = null;
  for (var j = 1; j < row.length; j++) {
    var c = String(row[j] || '').trim();
    var mk = c.match(/^([A-Za-z]+)\s*\n?\s*(\d{4})$/);
    if (mk) { year = +mk[2]; continue; }
    var m = c.match(/(\d{1,2})[\/.](\d{1,2})$/);
    if (!m) continue;
    var d = +m[1], mo = +m[2] - 1;
    if (year === null) year = fallbackYear - 2; // first columns before any marker (e.g. Oct 2024)
    if (lastMonth !== null && mo < lastMonth && !mk) { if (lastMonth === 11 && mo === 0) year++; }
    lastMonth = mo;
    var dt = new Date(year, mo, d);
    map[bkKey_(dt)] = j; last = dt;
  }
  return {map: map, last: last};
}
function bkKey_(d) { return d.getFullYear() + '-' + (d.getMonth() + 1) + '-' + d.getDate(); }

return {bookingsToday_: bookingsToday_, dryRunBookings: dryRunBookings};
})(T_props_('BKG'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);
