/** GENERATED by build-test-project.sh from schedule-coverage.gs — do not edit here. Module SC (TEST sandbox). */
var SC = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — М-3.1 Staff schedule coverage check (Schedule 26). DRAFT TEMPLATE, NOT DEPLOYED.
 *
 * Reads the Schedule-26 month tabs (same layout as stage5-timesheet.gs:
 * Position | Name | 1..31 | Total Hrs.) for the next WINDOW_DAYS and reports:
 *   - hours between OPEN_HOUR and CLOSE_HOUR with NO admin on shift (gaps)
 *   - hours with only one admin (info, e.g. reception cannot be left)
 *   - leave marks (Annual / Sick / Leave without money) and days with >= 2 admins on leave
 *   - next month tab missing (e.g. Nov not created by the 20th)
 *   - unreadable cells
 * Read-only on the sheet. Output: log (dryRun) or a Gmail DRAFT to info@ (draft mode). Never sends.
 * Intended use: Monday digest inside the existing 10:07 run (Lead reads the draft/log);
 * no new Lead runs. Owner of the schedule from 01.10: per George 29.09 "Lena + Place Ops"
 * — the Lena part is only a proposal, not agreed.
 *
 * Script Properties (all optional):
 *   SCHEDULE_SHEET_ID  default Schedule 26 id
 *   TAB_NAMES          JSON 12 names, default Jan..Dec
 *   POSITION_COL=A NAME_COL=B  HEADER_SCAN_ROWS=10
 *   ADMIN_RE           regex for admin rows, default 'admin'
 *   EXCLUDE_NAMES      comma list (e.g. 'Aiz' after 30.09)
 *   OPEN_HOUR=8 CLOSE_HOUR=23 WINDOW_DAYS=14
 *   REPORT_SINGLE      'true' = also list hours with only one admin (default off, noisy)
 *   COVERAGE_MODE      'dry' | 'draft'   DIGEST_TO default info@placecoworking.com
 */

var SC_TZ = 'Asia/Bangkok';
var SC_DEFAULT_ID = '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc';
var SC_TABS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
var SC_LEAVE_RE = /(annual|sick|leave|unpaid|doctor|ลา|ป่วย|พักร้อน)/i;
var SC_OFF_RE = /^(off|day\s*off|หยุด|-|x)$/i;

function dryRunCoverage() { return coverage_('dry'); }
function runCoverage() { var m = PropertiesService.getScriptProperties().getProperty('COVERAGE_MODE') || 'dry'; return coverage_(m === 'draft' ? 'draft' : 'dry'); }

function scCfg_() {
  var p = PropertiesService.getScriptProperties();
  var g = function (k, d) { var v = p.getProperty(k); return (v === null || v === '') ? d : v; };
  return {
    id: g('SCHEDULE_SHEET_ID', SC_DEFAULT_ID), tabs: JSON.parse(g('TAB_NAMES', JSON.stringify(SC_TABS))),
    posCol: scCol_(g('POSITION_COL', 'A')), nameCol: scCol_(g('NAME_COL', 'B')), scan: Number(g('HEADER_SCAN_ROWS', '10')),
    adminRe: new RegExp(g('ADMIN_RE', 'admin'), 'i'),
    exclude: g('EXCLUDE_NAMES', '').split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(String),
    open: Number(g('OPEN_HOUR', '8')), close: Number(g('CLOSE_HOUR', '23')), win: Number(g('WINDOW_DAYS', '14')),
    to: g('DIGEST_TO', 'info@placecoworking.com'), single: g('REPORT_SINGLE', 'false') === 'true'
  };
}

function coverage_(mode) {
  var c = scCfg_(), ss = SpreadsheetApp.openById(c.id);
  var s = Utilities.formatDate(new Date(), SC_TZ, 'yyyy-MM-dd').split('-');
  var start = new Date(+s[0], +s[1] - 1, +s[2]);
  var cache = {}, lines = [], warn = [], gapsTotal = 0;
  for (var i = 0; i < c.win; i++) {
    var d = new Date(start.getFullYear(), start.getMonth(), start.getDate() + i);
    var tab = c.tabs[d.getMonth()];
    if (!(tab in cache)) cache[tab] = scReadTab_(ss.getSheetByName(tab), c);
    var mdata = cache[tab];
    if (!mdata) { if (warn.indexOf('Нет вкладки ' + tab) < 0) warn.push('Нет вкладки ' + tab + ' (график на ' + tab + ' не составлен)'); continue; }
    var slots = [], leave = [], unknown = [];
    for (var h = c.open; h < c.close; h++) slots.push([]);
    mdata.people.forEach(function (p) {
      var raw = p.days[d.getDate()] || '';
      if (!raw) return;
      var sh = scShift_(raw);
      if (sh) { for (var h = c.open; h < c.close; h++) if (scCovers_(sh, h)) slots[h - c.open].push(p.name); return; }
      if (SC_LEAVE_RE.test(raw)) { leave.push(p.name + ' (' + raw + ')'); return; }
      if (SC_OFF_RE.test(raw)) return;
      unknown.push(p.name + ' "' + raw + '"');
    });
    var gaps = [], single = [];
    slots.forEach(function (arr, k) { var h = c.open + k; if (!arr.length) gaps.push(h); else if (arr.length === 1) single.push(h); });
    gapsTotal += gaps.length;
    var label = Utilities.formatDate(d, SC_TZ, 'EEE dd.MM');
    var parts = [];
    if (gaps.length) parts.push('🔴 НЕТ админа: ' + scRanges_(gaps));
    if (single.length && c.single) parts.push('🟡 один админ: ' + scRanges_(single));
    if (leave.length) parts.push((leave.length >= 2 ? '⚠️ ' : '') + 'отпуск/больничный: ' + leave.join(', '));
    if (unknown.length) parts.push('❓ ' + unknown.join('; '));
    if (parts.length) lines.push(label + ': ' + parts.join(' · '));
  }
  // next month tab must exist by the 20th
  if (start.getDate() >= 20) { var nt = c.tabs[(start.getMonth() + 1) % 12]; if (!ss.getSheetByName(nt)) warn.push('К 20-му нет вкладки следующего месяца: ' + nt); }
  var subject = 'Покрытие смен ' + Utilities.formatDate(start, SC_TZ, 'dd.MM') + ' + ' + c.win + ' дн.: дыр ' + gapsTotal + ' ч';
  var body = (lines.length ? lines.join('\n') : 'Дыр и отпусков нет.') + (warn.length ? '\n\n' + warn.join('\n') : '') +
    '\n\nЧасы ' + c.open + ':00–' + c.close + ':00, только строки Admin. Черновик, никому не отправлено.';
  if (mode === 'draft') GmailApp.createDraft(c.to, subject, body);
  Logger.log('[coverage ' + mode + '] ' + subject + '\n' + body);
  return {subject: subject, body: body, gaps: gapsTotal};
}

function scReadTab_(sh, c) {
  if (!sh) return null;
  var vals = sh.getDataRange().getValues(), disp = sh.getDataRange().getDisplayValues();
  var hdr = null;
  for (var r = 0; r < Math.min(c.scan, vals.length) && !hdr; r++) {
    var cols = {}, n = 0;
    for (var j = 0; j < vals[r].length; j++) {
      var v = vals[r][j], day = v instanceof Date ? v.getDate() : (/^\d{1,2}$/.test(String(v).trim()) ? Number(v) : null);
      if (day && day <= 31 && cols[day] === undefined) { cols[day] = j; n++; }
    }
    if (n >= 28 && cols[1] !== undefined) hdr = {row: r, cols: cols};
  }
  if (!hdr) return {people: []};
  var people = [], lastPos = '';
  for (var r2 = hdr.row + 1; r2 < disp.length; r2++) {
    var pos = String(disp[r2][c.posCol] || '').trim(), name = String(disp[r2][c.nameCol] || '').trim();
    if (pos) lastPos = pos;
    if (!name || !c.adminRe.test(lastPos) || c.exclude.indexOf(name.toLowerCase()) >= 0) continue;
    var days = {};
    Object.keys(hdr.cols).forEach(function (dd) { days[dd] = String(disp[r2][hdr.cols[dd]] || '').trim(); });
    people.push({name: name, pos: lastPos, days: days});
  }
  return {people: people};
}

/** "8:00-17:00", "14.00 – 23.00", "8-17", "23:00-8:00" -> {a, b} in hours (b may be > 24). */
function scShift_(raw) {
  var m = raw.replace(/\s+/g, '').match(/^(\d{1,2})(?:[:.](\d{2}))?[-–—~]+(\d{1,2})(?:[:.](\d{2}))?$/);
  if (!m) return null;
  var a = +m[1] + (+m[2] || 0) / 60, b = +m[3] + (+m[4] || 0) / 60;
  if (a > 24 || b > 24) return null;
  if (b <= a) b += 24;
  return {a: a, b: b};
}
function scCovers_(sh, h) { return (sh.a <= h && sh.b >= h + 1) || (sh.a <= h + 24 && sh.b >= h + 25); }
function scRanges_(hours) {
  var out = [], s = hours[0], p = hours[0];
  for (var i = 1; i <= hours.length; i++) {
    if (hours[i] === p + 1) { p = hours[i]; continue; }
    out.push(s + ':00–' + (p + 1) + ':00'); s = p = hours[i];
  }
  return out.join(', ');
}
function scCol_(l) { var s = String(l).toUpperCase(), n = 0; for (var i = 0; i < s.length; i++) n = n * 26 + s.charCodeAt(i) - 64; return n - 1; }

return {coverage_: coverage_, scCfg_: scCfg_, scReadTab_: scReadTab_, scShift_: scShift_};
})(T_props_('SC'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);
