/** GENERATED by build-test-project.sh from cash-collection.gs — do not edit here. Module CASH (TEST sandbox). */
var CASH = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — cash collection every 3 days (George 01.10.2026). DRAFT, NOT DEPLOYED (TEST only).
 *
 * Process:
 *   - every 3 days at 20:00 the evening admin gets a short reminder (any amount; no cash → no collection);
 *   - after closing the admin counts and writes to the bot, no photo: «в кассе X / в сейф Y»
 *     (also «in till X / safe Y», «ลิ้นชัก X / เซฟ Y»); the surplus Y goes into the safe; the same figures go into the act;
 *   - then Khun Sak gets a DM: money is in the safe, please come by.
 *
 * Receiving the admin's reply needs the bridge hook (live bridge is NOT changed now). Hook, when approved:
 *   if (m.chat.type === 'private' && CASH_RE.test(text)) try { cashHandleReply_(text, name, new Date()); } catch (e) { Logger.log('CASH_ERR ' + e); }
 * Script Properties (production): TOKEN (bridge bot), SAK_CHAT_ID (Khun Sak's private chat). Empty → WARN, nothing sent.
 */
var CASH_TZ = 'Asia/Bangkok';
var CASH_RE = /(в\s*кассе|касса|in\s*till|till|ลิ้นชัก)\s*[:=-]?\s*\d/i;

/** 20:00 reminder for the evening admin (EN + TH, short). */
function cashReminderText_() {
  return '💰 Cash collection today\n' +
    'After closing, reply here (no photo): «в кассе X / в сейф Y». Same figures in the act. No cash → no collection.\n' +
    'วันนี้เก็บเงินสด: หลังปิดร้านพิมพ์ «ลิ้นชัก X / เซฟ Y» ตัวเลขเดียวกันลงใบส่งมอบ ไม่มีเงินสด = ไม่ต้องเก็บ';
}

function cashNum_(s) { return Number(String(s).replace(/[\s,]/g, '')); }
function cashFmt_(n) { return String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ' ') + ' ฿'; }

/** «в кассе 2 000 / в сейф 12 500» → {till: 2000, safe: 12500} or null. */
function cashParse_(text) {
  var t = String(text || '');
  var a = t.match(/(?:в\s*кассе|касса|in\s*till|till|ลิ้นชัก)\s*[:=-]?\s*([\d][\d\s,]*)/i);
  var b = t.match(/(?:в\s*сейф|сейф|to\s*safe|safe|เซฟ|ตู้เซฟ)\s*[:=-]?\s*([\d][\d\s,]*)/i);
  if (!a || !b) return null;
  var till = cashNum_(a[1]), safe = cashNum_(b[1]);
  if (isNaN(till) || isNaN(safe)) return null;
  return {till: till, safe: safe};
}

/** Builds the texts for a reply. Returns {ok, till, safe, ack, sak} (sak = '' when nothing went to the safe). */
function cashReply_(text, admin, now) {
  var v = cashParse_(text);
  if (!v) return {ok: false, ack: 'Format: «в кассе X / в сейф Y» · รูปแบบ: «ลิ้นชัก X / เซฟ Y»'};
  var when = Utilities.formatDate(now || new Date(), CASH_TZ, 'dd.MM HH:mm');
  var sak = v.safe > 0 ? '💰 In the safe: ' + cashFmt_(v.safe) + ' (' + admin + ', ' + when + '). Please come by.\nเงินในเซฟ ' + cashFmt_(v.safe) + ' กรุณามารับ' : '';
  return {ok: true, till: v.till, safe: v.safe, sak: sak,
    ack: '✅ Till ' + cashFmt_(v.till) + ' / safe ' + cashFmt_(v.safe) + (sak ? ' · Khun Sak notified' : ' · no collection')};
}

/** Production: handle the admin's reply (needs the bridge hook) → DM to Khun Sak. */
function cashHandleReply_(text, admin, now) {
  var r = cashReply_(text, admin, now);
  if (!r.ok || !r.sak) return r;
  var p = PropertiesService.getScriptProperties(), chat = String(p.getProperty('SAK_CHAT_ID') || '').trim(), tok = p.getProperty('TOKEN');
  if (!chat || !tok) { Logger.log('WARN ' + (!chat ? 'SAK_CHAT_ID' : 'TOKEN') + ' not set → Sak NOT notified'); r.sent = false; return r; }
  var x = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
    payload: JSON.stringify({chat_id: chat, text: r.sak}), muteHttpExceptions: true});
  r.sent = x.getResponseCode() === 200;
  return r;
}

return {cashReminderText_: cashReminderText_, cashParse_: cashParse_, cashReply_: cashReply_, cashHandleReply_: cashHandleReply_};
})(T_props_('CASH'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);
