/** GENERATED by build-test-project.sh from cash-collection.gs — do not edit here. Module CASH (TEST sandbox). */
var CASH = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — cash collection every 3 days (George 01.10.2026 12:05 + correction 12:06). DRAFT, NOT DEPLOYED (TEST only).
 *
 * Process (the safe has a DROP SLOT: the admin reports only what they put in; the script keeps the running total):
 *   - every 3 days at 22:30 the evening admin gets a short reminder (PLACE Team → ENGLISH ONLY, George 05.10); any amount; no cash → no collection;
 *   - after closing the admin writes to the bot, no photo: «в кассе X / положил в сейф Y» (also «till X / deposited Y»,
 *     «ลิ้นชัก X / ใส่เซฟ Y»); the same figures go into the act;
 *   - the script adds Y to the safe counter (Script Property CASH_SAFE, since the last pickup);
 *   - if Y > 0, Khun Sak gets a DM «💰 In the safe: TOTAL ฿ (+Y today, admin). Please come by.» (+ TH); Y = 0 → no DM;
 *   - Sak replies «забрал» / «taken» / «รับแล้ว» → the counter is reset to 0.
 *
 * Receiving replies needs the bridge hook (live bridge is NOT changed now). Hooks, when approved:
 *   if (m.chat.type === 'private' && CASH_RE.test(text)) try { cashHandleReply_(text, name, new Date()); } catch (e) { Logger.log('CASH_ERR ' + e); }
 *   if (String(m.chat.id) === SAK_CHAT_ID && CASH_PICKUP_RE.test(text)) try { cashPickup_(text, name, new Date()); } catch (e) { Logger.log('CASH_ERR ' + e); }
 * Script Properties (production): TOKEN (bridge bot), SAK_CHAT_ID (Khun Sak's private chat), CASH_SAFE (counter, written by the script).
 */
var CASH_TZ = 'Asia/Bangkok';
var CASH_RE = /(в\s*кассе|касса|in\s*till|till|ลิ้นชัก)\s*[:=-]?\s*\d/i;
var CASH_TILL_RE = /(?:в\s*кассе|касса|in\s*till|till|ลิ้นชัก)\s*[:=-]?\s*(\d[\d\s,]*)/i;
var CASH_PICKUP_RE = /(забрал|забрали|taken|picked\s*up|รับแล้ว)/i;
var CASH_DEP_RE = /(?:положил[аи]?\s*в\s*сейф|в\s*сейф|сейф|deposited(?:\s*to\s*safe)?|to\s*safe|safe|ใส่เซฟ|ใส่ตู้เซฟ|ตู้เซฟ|เซฟ)\s*[:=-]?\s*(\d[\d\s,]*)/i;

/** 22:30 reminder for the evening admin (goes to PLACE Team: English only, short — George 05.10). Replies in RU/TH still parse. */
function cashReminderText_() {
  return '💰 Cash collection today. After closing reply here (no photo): «till X / deposited Y». Same figures in the act. No cash → no collection.';
}

function cashNum_(s) { return Number(String(s).replace(/[\s,]/g, '')); }
function cashFmt_(n) { return String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g, ' ') + ' ฿'; }

/** «в кассе 2 000 / положил в сейф 12 500» → {till: 2000, deposited: 12500} or null. */
function cashParse_(text) {
  var t = String(text || ''), a = t.match(CASH_TILL_RE), b = t.match(CASH_DEP_RE);
  if (!a || !b) return null;
  var till = cashNum_(a[1]), dep = cashNum_(b[1]);
  if (isNaN(till) || isNaN(dep)) return null;
  return {till: till, deposited: dep};
}

/** Safe counter since the last pickup: {total, since, n}. */
function cashSafe_() {
  var v = PropertiesService.getScriptProperties().getProperty('CASH_SAFE');
  try { return v ? JSON.parse(v) : {total: 0, since: '', n: 0}; } catch (e) { return {total: 0, since: '', n: 0}; }
}
function cashSafeSave_(o) { PropertiesService.getScriptProperties().setProperty('CASH_SAFE', JSON.stringify(o)); }

/** Admin's reply → adds Y to the counter. Returns {ok, till, deposited, total, ack, sak}; sak = '' when Y = 0 (no DM). */
function cashReply_(text, admin, now) {
  var v = cashParse_(text);
  if (!v) return {ok: false, ack: 'Format: «till X / deposited Y»'};
  var safe = cashSafe_();
  if (v.deposited > 0) {
    safe.total = (Number(safe.total) || 0) + v.deposited; safe.n = (safe.n || 0) + 1;
    if (!safe.since) safe.since = Utilities.formatDate(now || new Date(), CASH_TZ, 'yyyy-MM-dd HH:mm');
    cashSafeSave_(safe);
  }
  var sak = v.deposited > 0 ? '💰 In the safe: ' + cashFmt_(safe.total) + ' (+' + cashFmt_(v.deposited) + ' today, ' + admin + '). Please come by.\n' +
    '💰 ในเซฟ: ' + cashFmt_(safe.total) + ' (+' + cashFmt_(v.deposited) + ' วันนี้, ' + admin + ') กรุณามารับ' : '';
  return {ok: true, till: v.till, deposited: v.deposited, total: Number(safe.total) || 0, sak: sak,
    ack: '✅ Till ' + cashFmt_(v.till) + ' · deposited ' + cashFmt_(v.deposited) + (sak ? ' · Khun Sak notified' : ' · no collection')};
}

/** Sak's reply «забрал» / «taken» / «รับแล้ว» → counter reset. Returns {ok, taken, ack}. */
function cashPickup_(text, who, now) {
  if (!CASH_PICKUP_RE.test(String(text || ''))) return {ok: false, ack: ''};
  var safe = cashSafe_(), taken = Number(safe.total) || 0;
  cashSafeSave_({total: 0, since: '', n: 0, lastPickup: Utilities.formatDate(now || new Date(), CASH_TZ, 'yyyy-MM-dd HH:mm') + ' ' + (who || '') + ' ' + taken});
  return {ok: true, taken: taken, ack: '✅ Taken: ' + cashFmt_(taken) + '. Counter reset · รับแล้ว ' + cashFmt_(taken)};
}

/** Production: handle the admin's reply (needs the bridge hook) → DM to Khun Sak. */
function cashHandleReply_(text, admin, now) {
  var r = cashReply_(text, admin, now);   // updates the counter
  if (!r.ok || !r.sak) return r;
  var p = PropertiesService.getScriptProperties(), chat = String(p.getProperty('SAK_CHAT_ID') || '').trim(), tok = p.getProperty('TOKEN');
  if (!chat || !tok) { Logger.log('WARN ' + (!chat ? 'SAK_CHAT_ID' : 'TOKEN') + ' not set → Sak NOT notified'); r.sent = false; return r; }
  var x = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
    payload: JSON.stringify({chat_id: chat, text: r.sak}), muteHttpExceptions: true});
  r.sent = x.getResponseCode() === 200;
  return r;
}

return {cashReminderText_: cashReminderText_, cashParse_: cashParse_, cashReply_: cashReply_, cashHandleReply_: cashHandleReply_, cashPickup_: cashPickup_, cashSafe_: cashSafe_, cashSafeSave_: cashSafeSave_};
})(T_props_('CASH'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);
