#!/usr/bin/env bash
# Builds the TEST Apps Script files: each production draft .gs is wrapped in a function scope whose
# Google services are the T_* safety stubs from 00-TestConfig.gs. Sources stay unchanged.
set -euo pipefail
cd "$(dirname "$0")"
S=..
wrap() { # $1 out  $2 module  $3 source  $4 exports  $5 prelude
  { echo "/** GENERATED by build-test-project.sh from $3 — do not edit here. Module $2 (TEST sandbox). */"
    echo "var $2 = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {"
    echo "${5:-}"
    cat "$S/$3"
    echo ""
    echo "return {$4};"
    echo "})(T_props_('$2'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);"
  } > "$1"
}
wrap 10-Stage6.gs     ST6 stage6-office-reminders.gs 'dryRun: dryRun, run_: run_, resetSentLog: resetSentLog'
wrap 20-IssuesLog.gs  ISS issues-log.gs 'issuesSheet_: issuesSheet_, issuesHandle_: issuesHandle_, issuesDigest_: issuesDigest_, issuesSendDigest_: issuesSendDigest_, issuesThreads_: issuesThreads_, issuesEssence_: issuesEssence_, ISSUES_HEAD: ISSUES_HEAD, ISSUES_CHAT_RE: ISSUES_CHAT_RE' 'var SHEET_ID = T_IDS.inbox; // TEST: Place Inbox TEST, never the live bridge sheet'
wrap 30-Bookings.gs   BKG bookings-today.gs 'bookingsToday_: bookingsToday_, dryRunBookings: dryRunBookings'
wrap 40-Keyholders.gs KH  keyholders-247.gs 'keyholders247_: keyholders247_'
wrap 50-Timesheet.gs  ST5 stage5-timesheet.gs 'dryRun: dryRun, createTimesheetDraft: createTimesheetDraft'
wrap 70-Leave.gs     LV  leave-requests.gs 'leaveParse_: leaveParse_, leaveRequest_: leaveRequest_, leaveDecide_: leaveDecide_'
wrap 80-Payments.gs  PAY payment-reminders.gs 'PAY_SCHEDULE: PAY_SCHEDULE, payDue_: payDue_, payText_: payText_, payRemindersRun_: payRemindersRun_'
wrap 85-Cash.gs      CASH cash-collection.gs 'cashReminderText_: cashReminderText_, cashParse_: cashParse_, cashReply_: cashReply_, cashHandleReply_: cashHandleReply_, cashPickup_: cashPickup_, cashSafe_: cashSafe_, cashSafeSave_: cashSafeSave_'
wrap 60-Coverage.gs   SC  schedule-coverage.gs 'coverage_: coverage_, scCfg_: scCfg_, scReadTab_: scReadTab_, scShift_: scShift_'
# appsscript.json manifest
cat > appsscript.json <<'J'
{ "timeZone": "Asia/Bangkok", "runtimeVersion": "V8", "exceptionLogging": "STACKDRIVER",
  "oauthScopes": ["https://www.googleapis.com/auth/spreadsheets", "https://www.googleapis.com/auth/script.scriptapp", "https://www.googleapis.com/auth/script.external_request"] }
J
echo built: $(ls *.gs)
# single-file bundle (same order 00 -> 90) for copy-paste into one Code.gs
{ echo "// PLACE automations TEST — single-file bundle, generated by build-test-project.sh. Do not edit by hand."; for f in 00-TestConfig.gs 10-Stage6.gs 20-IssuesLog.gs 30-Bookings.gs 40-Keyholders.gs 50-Timesheet.gs 60-Coverage.gs 70-Leave.gs 80-Payments.gs 85-Cash.gs 90-Tests.gs 95-Scheduled.gs; do echo; echo "// ===== $f ====="; cat "$f"; done; } > PLACE-automations-TEST.bundle.gs
echo bundle: PLACE-automations-TEST.bundle.gs
