// PLACE automations TEST — single-file bundle, generated by build-test-project.sh. Do not edit by hand.

// ===== 00-TestConfig.gs =====
/**
 * PLACE automations TEST — config, safety layer, relay to George. George OK 30.09.2026 10:02: SCHEDULED TEST MODE.
 *
 * Modules 10-*.gs … 60-*.gs are generated by build-test-project.sh. Each runs inside a function wrapper whose
 * PropertiesService / SpreadsheetApp / GmailApp / MailApp / UrlFetchApp / ScriptApp / Logger are the T_* objects below.
 *
 * SAFETY
 *   - Production sheets (Resident info, Schedule 26, Events and booking, Place Inbox / orders bridge) open READ-ONLY:
 *     every method except get…, is…, has… throws «TEST GUARD». Writes are possible only in the TEST copies (T_IDS),
 *     in practice only Issues + Log in «Place Inbox TEST». Any other spreadsheet id throws.
 *   - NOTHING goes to its real target. GmailApp.createDraft/sendEmail, MailApp and Telegram sendMessage from modules are
 *     intercepted and RELAYED to George's private chat with @PlaceLeadBot as
 *       «🧪 TEST, would be sent to: <recipient> via <channel>, at <time>» + the exact text.
 *     T_relay_ can only send to Script Property GEORGE_CHAT_ID and only if it is a private chat id (positive number).
 *     Without TG_TOKEN or GEORGE_CHAT_ID the relay is LOG ONLY (tab Log).
 *   - The bot token is NEVER in code: set Script Property TG_TOKEN by hand (Project Settings ▸ Script properties).
 *   - The live bridge is not touched. «Тех вопросы» messages are read read-only from the production queue tab.
 * Fixture tests (test_*) use the TEST copies and never relay (log only).
 */
var T_IDS = {  // TEST copies in «PLACE TEST sandbox» (writable)
  resident: '1THjNTF1S0Gu3aHeAD4vxK0Ylcf5BDhTqsL2GMaq8cH4', // Resident info TEST
  schedule: '13viAmqT1XMQ99twJw-u5AaTtHWSGPki0zzEX7PleYYg', // Schedule 26 TEST
  events:   '1kkVOqLqVMpwpZtYpshx3zvH5_EGJ7wYp69sKJJQw3Rk', // Events and booking TEST
  inbox:    '1fwjPnLM4JcBH8HnqayWMLdRznU2U7saJX3PQLa9-6GU'  // Place Inbox TEST (Issues, Log)
};
var P_IDS = {  // PRODUCTION (read-only through T_SS)
  resident: '1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4', // Resident info
  schedule: '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc', // Schedule 26
  events:   '1BSwm4sY-ksXjFNEEsAdyiWmUDzgbQlJpL_dh9JIdZAc', // Events and booking
  inbox:    '1uMHYp6d-Ji9VQj5xtESiXummBNX9bC8vTruPRQLs8jw'  // Place Inbox (orders bridge sheet, tab queue)
};
var T_PROD_IDS = Object.keys(P_IDS).map(function (k) { return P_IDS[k]; });
var T_LOG_TAB = 'Log';
var T_BOOKING_TABS = JSON.stringify(['Meeting room', '1 floor', '4 floor', 'ART Room ', '6 floor']);
/** Known Telegram chats -> human label for the «would be sent to» line. */
var T_CHAT_LABELS = {'-1003641241156': ['PLACE Team', 'TG group PLACE Team'], '626363253': ['Lena', 'TG DM Lena']};

var T_PROFILES = {
  /** fixture = synthetic data in the TEST copies (test_* functions, log only) */
  fixture: {
    ST6: {RESIDENT_SHEET_ID: T_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
          ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'test-digest@example.invalid', TODAY_OVERRIDE: '2026-09-30'},
    ISS: {ISSUES_MODE: 'live'},  // 'live' = writes to Issues in Place Inbox TEST only (SHEET_ID = T_IDS.inbox)
    BKG: {EVENTS_SHEET_ID: T_IDS.events, BOOKING_TABS: T_BOOKING_TABS},
    ST5: {SCHEDULE_SHEET_ID: T_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', ACCOUNTANT_TO: 'test-accountant@example.invalid'},
    KH:  {RESIDENT_SHEET_ID: T_IDS.resident, KEY_TAB: 'Лист1'},
    SC:  {SCHEDULE_SHEET_ID: T_IDS.schedule, EXCLUDE_NAMES: 'Aiz', COVERAGE_MODE: 'draft', DIGEST_TO: 'test-digest@example.invalid'},
    LV:  {LEAVE_SHEET_ID: T_IDS.inbox, SCHEDULE_SHEET_ID: T_IDS.schedule, LEAVE_APPROVER: 'George'}  // writes: Leave tab + Schedule 26 TEST
  },
  /** sched = scheduled TEST mode: production data read-only, writes only to Place Inbox TEST, every message relayed to George */
  sched: {
    ST6: {RESIDENT_SHEET_ID: P_IDS.resident, TAB_NAME: 'Office rent', MODE: 'draft', ELEC_TASK_MODE: 'issues',
          ISSUES_SHEET_ID: T_IDS.inbox, DIGEST_TO: 'info@placecoworking.com'},
    ISS: {ISSUES_MODE: 'live'},
    BKG: {EVENTS_SHEET_ID: P_IDS.events, BOOKING_TABS: T_BOOKING_TABS},
    ST5: {SCHEDULE_SHEET_ID: P_IDS.schedule, SHEET_YEAR: '2026', DRAFT_ENABLED: 'true', EXCLUDE_NAMES: '',
          ACCOUNTANT_TO: 'new accountant Pat (address not known yet; not configured in TEST)'},
    KH:  {RESIDENT_SHEET_ID: P_IDS.resident, KEY_TAB: 'Лист1'},
    SC:  {SCHEDULE_SHEET_ID: P_IDS.schedule, EXCLUDE_NAMES: 'Aiz', COVERAGE_MODE: 'draft', DIGEST_TO: 'info@placecoworking.com'},
    LV:  {LEAVE_SHEET_ID: T_IDS.inbox, SCHEDULE_SHEET_ID: T_IDS.schedule, LEAVE_APPROVER: 'George'}  // staged: TEST copies only, never production
  }
};
var T_PROFILE = 'fixture';
var T_CTX = {relay: false, mail: null};   // set per job: relay on/off, mail(to) -> {recipient, channel}
var T_RUNNER = 'apps-script';             // the node harness sets 'node-harness'
var T_BUF = [];                             // Logger lines of the current run

function T_now_() { return Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm:ss'); }
function T_log_(item, fn, result, details) {
  var sh = SpreadsheetApp.openById(T_IDS.inbox).getSheetByName(T_LOG_TAB);
  var row = [T_now_(), item, fn, T_RUNNER + ':' + T_PROFILE, String(result), T_mask_(String(details || '')).slice(0, 45000)];
  if (sh) sh.appendRow(row); else Logger.log(row.join(' | '));
}
function T_mask_(s) { return String(s).replace(/bot\d+:[A-Za-z0-9_-]+/g, 'bot***').replace(/\d{8,10}:[A-Za-z0-9_-]{30,}/g, '***'); }

// ---------- spreadsheets: TEST writable, production read-only ----------
var T_RO_ALLOW = /^(get|is|has|toString$)/;
function T_readOnly_(obj, where) {
  if (obj === null || typeof obj !== 'object') return obj;
  if (Array.isArray(obj)) return obj.map(function (x) { return T_readOnly_(x, where); });
  if (obj instanceof Date || Object.prototype.toString.call(obj) === '[object Date]') return obj;  // every other object (Spreadsheet, Sheet, Range, …) is wrapped
  return new Proxy({}, {
    get: function (_, prop) {
      if (typeof prop !== 'string') return undefined;
      if (!T_RO_ALLOW.test(prop)) return function () { throw new Error('TEST GUARD: production is read-only (' + where + '.' + prop + ')'); };
      var f = obj[prop];
      if (typeof f !== 'function') return f;
      return function () { return T_readOnly_(f.apply(obj, arguments), where); };
    },
    set: function () { throw new Error('TEST GUARD: production is read-only (' + where + ')'); }
  });
}
var T_SS = {
  openById: function (id) {
    if (T_PROD_IDS.indexOf(id) >= 0) return T_readOnly_(SpreadsheetApp.openById(id), 'prod:' + id.slice(0, 6));
    var ok = Object.keys(T_IDS).some(function (k) { return T_IDS[k] === id; });
    if (!ok) throw new Error('TEST GUARD: sheet is not in T_IDS/P_IDS ' + id);
    return SpreadsheetApp.openById(id);
  }
};

// ---------- per-module Script Properties ----------
function T_props_(mod) {
  var real = PropertiesService.getScriptProperties(), pre = 'T_' + mod + '_';
  var api = {
    getProperty: function (k) {
      var v = real.getProperty(pre + T_PROFILE + '_' + k); if (v !== null && v !== undefined) return v;
      var d = ((T_PROFILES[T_PROFILE] || {})[mod] || {})[k]; return d === undefined ? null : String(d);
    },
    setProperty: function (k, v) { real.setProperty(pre + T_PROFILE + '_' + k, v); return api; },
    deleteProperty: function (k) { real.deleteProperty(pre + T_PROFILE + '_' + k); return api; }
  };
  return { getScriptProperties: function () { return api; } };
}

// ---------- relay: the ONLY outgoing channel (George's DM) ----------
function T_relay_(recipient, channel, text) {
  var head = '🧪 TEST, would be sent to: ' + recipient + ' via ' + channel + ', at ' + T_now_();
  var full = head + '\n\n' + text;
  if (!T_CTX.relay) { T_BUF.push('[relay off: fixture test]\n' + full); return 'log-only(fixture)'; }
  var p = PropertiesService.getScriptProperties(), tok = p.getProperty('TG_TOKEN'), chat = p.getProperty('GEORGE_CHAT_ID');
  if (!tok || !chat || !/^\d{5,15}$/.test(chat)) {   // private chats only; groups have negative ids
    T_BUF.push('[relay LOG ONLY: ' + (!tok ? 'TG_TOKEN not set' : 'GEORGE_CHAT_ID not set/invalid') + ']\n' + full);
    return 'log-only';
  }
  var parts = [], s = full;
  while (s.length) { parts.push(s.slice(0, 3900)); s = s.slice(3900); }
  var codes = parts.map(function (part, i) {
    var r = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
      payload: JSON.stringify({chat_id: chat, text: (i ? '🧪 (cont.)\n' : '') + part, disable_web_page_preview: true}), muteHttpExceptions: true});
    return r.getResponseCode();
  });
  T_BUF.push('[relayed to George, HTTP ' + codes.join(',') + ']\n' + full);
  return 'relayed:' + codes.join(',');
}
function T_mailTarget_(to) { return T_CTX.mail ? T_CTX.mail(to) : {recipient: to, channel: 'email draft (info@) to ' + to}; }
var T_GMAIL = {
  createDraft: function (to, subject, body, opts) {
    var t = T_mailTarget_(to);
    T_relay_(t.recipient, t.channel, 'Subject: ' + subject + (opts && opts.cc ? '\nCc: ' + opts.cc : '') +
      (opts && opts.attachments ? '\nAttachments: ' + opts.attachments.length : '') + '\n\n' + body);
    return { getId: function () { return 'TEST-RELAYED'; } };
  },
  sendEmail: function (to, subject, body) { var t = T_mailTarget_(to); T_relay_(t.recipient, 'email to ' + to, 'Subject: ' + subject + '\n\n' + body); }
};
var T_MAIL = { sendEmail: function (to, subject, body) { T_GMAIL.sendEmail(to, subject, body); } };
var T_FETCH = {
  fetch: function (u, o) {
    var url = String(u);
    if (/api\.telegram\.org\/bot[^/]+\/sendMessage/.test(url)) {
      var pl = {}; try { pl = JSON.parse((o && o.payload) || '{}'); } catch (e) {}
      var lab = T_CHAT_LABELS[String(pl.chat_id)] || ['chat ' + pl.chat_id, 'TG chat ' + pl.chat_id];
      T_relay_(lab[0], lab[1], String(pl.text || ''));
      return { getResponseCode: function () { return 200; }, getContentText: function () { return '{"ok":true,"test":true}'; } };
    }
    throw new Error('TEST GUARD: UrlFetchApp blocked in modules: ' + T_mask_(url));
  }
};
var T_SCRIPT = {
  getProjectTriggers: function () { return []; },
  newTrigger: function () { throw new Error('TEST GUARD: modules cannot create triggers (use installTestTriggers)'); },
  deleteTrigger: function () {}
};
var T_LOGGER = { log: function (x) { T_BUF.push(typeof x === 'string' ? x : JSON.stringify(x)); } };

/** Runs fn, writes result + Logger lines to Log. Never throws (error is logged). */
function T_run_(item, fnName, fn) {
  T_BUF = [];
  var res, status;
  try { res = fn(); status = 'OK'; } catch (e) { res = e && e.message; status = 'ERROR'; }
  var details = (typeof res === 'string' ? res : JSON.stringify(res)) + (T_BUF.length ? '\n--- log ---\n' + T_BUF.join('\n') : '');
  T_log_(item, fnName, status, details);
  return {status: status, result: res, log: T_BUF.slice()};
}
/** Scheduled job: production read-only, relay on. */
function T_job_(item, fnName, mail, fn) {
  var prev = [T_PROFILE, T_CTX];
  T_PROFILE = 'sched'; T_CTX = {relay: true, mail: mail || null};
  try { return T_run_(item, fnName, fn); } finally { T_PROFILE = prev[0]; T_CTX = prev[1]; }
}
/** Fixture test: TEST copies, relay off. */
function T_fixture_(item, fnName, fn) {
  var prev = [T_PROFILE, T_CTX];
  T_PROFILE = 'fixture'; T_CTX = {relay: false, mail: null};
  try { return T_run_(item, fnName, fn); } finally { T_PROFILE = prev[0]; T_CTX = prev[1]; }
}

// ===== 10-Stage6.gs =====
/** GENERATED by build-test-project.sh from stage6-office-reminders.gs — do not edit here. Module ST6 (TEST sandbox). */
var ST6 = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — Stage 6 (2.1.9 / 2.1.10 / 5.1.5 Offices). DRAFT TEMPLATE, NOT DEPLOYED.
 *
 * Reads the office tenants table (proposed: the empty tab "Office rent" in
 * Resident info, columns see STAGES-5-6.md) and prepares reminders:
 *   - payment due in N days (default 7,3,0)
 *   - contract end in N days (default 30,7)
 *   - deposit not paid (deposit amount > 0 and no deposit paid date)
 *   - room overlap (two active contracts on the same room, e.g. 5th floor room 3)
 *
 * MODES (Script Property MODE):
 *   'dry'   (default) — log only, nothing is created.
 *   'draft' — creates Gmail DRAFTS (tenant reminders + one internal digest). Never sends.
 * There is intentionally NO send mode. Sending stays manual until George approves.
 * The script never writes to the sheet; "already reminded" is kept in Script Properties.
 *
 * Script Properties:
 *   RESIDENT_SHEET_ID   default 1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4 (Resident info)
 *   TAB_NAME            default 'Office rent'
 *   HEADER_ROW          default 1
 *   PAYMENT_DAYS        default '7,3,0'
 *   CONTRACT_DAYS       default '30,7'
 *   DIGEST_TO           internal recipient of the digest draft, default info@placecoworking.com
 *   MODE                'dry' | 'draft'
 *   TENANT_DRAFTS       'true' (default) = also create per-tenant drafts in draft mode
 *   COL_*               header overrides, e.g. COL_EMAIL='E-mail' (see HEADERS below)
 *   ELEC_TASK_MODE      'dry' (default, log only) | 'issues' = (only with MODE=draft) append a row to the «Issues»
 *                       tech-task tab (see issues-log.gs). No TG post from here.
 *   ISSUES_SHEET_ID     spreadsheet with the «Issues» tab (Place Inbox), required for 'issues'
 *   TODAY_OVERRIDE      yyyy-mm-dd, TEST ONLY: pretend today is this date (fixtures in the TEST sandbox)
 *
 * ELECTRICITY BILL TASK (George 29.09): on the first day of each tenant's rent
 * month (= day-of-month of «Contract start», e.g. start 10.09 -> every 10th;
 * 31st -> last day of shorter months) create a tech task
 * «выставить счёт за электричество: <office>, <tenant>». Deduplicated per month.
 *
 * Time zone of the project: (GMT+07:00) Bangkok.
 * Principle (George 29.09): no new separate runs. Preferred: Lead calls dryRun()
 * results inside the existing 10:07 run. installDailyTrigger() is here only as
 * an option and must NOT be run without George OK.
 */

var TZ = 'Asia/Bangkok';
var DEFAULT_SHEET_ID = '1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4';
var HEADERS = { // logical key -> default header text in the sheet
  tenant: 'Tenant', contact: 'Contact name', email: 'Email', floor: 'Floor', room: 'Office/Room',
  start: 'Contract start', end: 'Contract end', term: 'Term', rent: 'Monthly rent',
  deposit: 'Deposit amount', depositPaid: 'Deposit paid date', nextPay: 'Next payment date',
  lastPaid: 'Last paid date', status: 'Status', lang: 'Language', notes: 'Notes'
};

// ---------- entry points ----------

function dryRun() { return run_('dry'); }

/** Draft mode only if MODE=draft; otherwise behaves as dryRun. */
function runReminders() {
  var mode = PropertiesService.getScriptProperties().getProperty('MODE') || 'dry';
  return run_(mode === 'draft' ? 'draft' : 'dry');
}

/** OPTIONAL, do not run without George OK. Daily 09:30 ICT. */
function installDailyTrigger() {
  ScriptApp.getProjectTriggers().forEach(function (t) { if (t.getHandlerFunction() === 'runReminders') ScriptApp.deleteTrigger(t); });
  ScriptApp.newTrigger('runReminders').timeBased().everyDays(1).atHour(9).nearMinute(30).inTimezone(TZ).create();
}

/** Clears the "already reminded" memory (e.g. after testing). */
function resetSentLog() { PropertiesService.getScriptProperties().deleteProperty('SENT_LOG'); }

// ---------- core ----------

function cfg_() {
  var p = PropertiesService.getScriptProperties();
  var g = function (k, d) { var v = p.getProperty(k); return (v === null || v === '') ? d : v; };
  var cols = {};
  Object.keys(HEADERS).forEach(function (k) { cols[k] = g('COL_' + k.toUpperCase(), HEADERS[k]); });
  var nums = function (s) { return s.split(',').map(function (x) { return Number(x.trim()); }).filter(function (x) { return !isNaN(x); }); };
  return {
    sheetId: g('RESIDENT_SHEET_ID', DEFAULT_SHEET_ID), tab: g('TAB_NAME', 'Office rent'),
    headerRow: Number(g('HEADER_ROW', '1')), cols: cols,
    payDays: nums(g('PAYMENT_DAYS', '7,3,0')), endDays: nums(g('CONTRACT_DAYS', '30,7')),
    digestTo: g('DIGEST_TO', 'info@placecoworking.com'), tenantDrafts: g('TENANT_DRAFTS', 'true') === 'true'
  };
}

function run_(mode) {
  var c = cfg_();
  var sh = SpreadsheetApp.openById(c.sheetId).getSheetByName(c.tab);
  if (!sh) throw new Error('Tab not found: ' + c.tab);
  var vals = sh.getDataRange().getValues();
  var head = vals[c.headerRow - 1].map(function (h) { return String(h).trim().toLowerCase(); });
  var idx = {}, missing = [];
  Object.keys(c.cols).forEach(function (k) { idx[k] = head.indexOf(c.cols[k].toLowerCase()); if (idx[k] < 0 && ['tenant', 'room', 'end', 'nextPay', 'email'].indexOf(k) >= 0) missing.push(c.cols[k]); });
  if (missing.length) throw new Error('Missing required columns: ' + missing.join(', '));

  var today = today_(), items = [], warnings = [], active = [];
  for (var r = c.headerRow; r < vals.length; r++) {
    var row = vals[r], get = function (k) { return idx[k] >= 0 ? row[idx[k]] : ''; };
    var t = {
      row: r + 1, tenant: String(get('tenant')).trim(), contact: String(get('contact')).trim(), email: String(get('email')).trim(),
      room: String(get('room')).trim(), floor: String(get('floor')).trim(), start: date_(get('start')), end: date_(get('end')),
      rent: get('rent'), deposit: Number(String(get('deposit')).replace(/[^\d.]/g, '')) || 0, depositPaid: date_(get('depositPaid')),
      nextPay: date_(get('nextPay')), status: String(get('status')).trim().toLowerCase(), lang: String(get('lang')).trim().toLowerCase()
    };
    if (!t.tenant) continue;
    if (/^(ended|closed|cancel)/.test(t.status)) continue;
    if (t.end && t.end < today) { warnings.push('Row ' + t.row + ' ' + t.tenant + ': contract ended ' + d_(t.end) + ' but status is not Ended'); continue; }
    active.push(t);
    if (t.nextPay) {
      var dp = diffDays_(today, t.nextPay);
      if (c.payDays.indexOf(dp) >= 0) items.push({type: 'PAYMENT', days: dp, t: t});
      else if (dp < 0) warnings.push('Row ' + t.row + ' ' + t.tenant + ': next payment date ' + d_(t.nextPay) + ' is in the past (overdue or not updated)');
    } else warnings.push('Row ' + t.row + ' ' + t.tenant + ': no next payment date');
    if (t.end) {
      var de = diffDays_(today, t.end);
      if (c.endDays.indexOf(de) >= 0) items.push({type: 'CONTRACT_END', days: de, t: t});
    }
    if (t.deposit > 0 && !t.depositPaid) items.push({type: 'DEPOSIT_UNPAID', days: null, t: t});
    if (!t.email) warnings.push('Row ' + t.row + ' ' + t.tenant + ': no email');
  }
  // room overlaps
  for (var i = 0; i < active.length; i++) for (var j = i + 1; j < active.length; j++) {
    var a = active[i], b = active[j];
    if (a.room && a.room === b.room && a.floor === b.floor && overlap_(a, b)) warnings.push('Room overlap: ' + a.floor + ' / ' + a.room + ' — ' + a.tenant + ' (row ' + a.row + ') and ' + b.tenant + ' (row ' + b.row + ')');
  }

  var log = JSON.parse(PropertiesService.getScriptProperties().getProperty('SENT_LOG') || '{}');
  var created = [];
  items.forEach(function (it) {
    var key = it.type + '|' + it.t.row + '|' + (it.type === 'PAYMENT' ? d_(it.t.nextPay) : d_(it.t.end)) + '|' + it.days;
    it.key = key; it.already = !!log[key];
    if (mode === 'draft' && c.tenantDrafts && !it.already && it.t.email && it.type !== 'DEPOSIT_UNPAID') {
      var m = tenantMail_(it);
      var d = GmailApp.createDraft(it.t.email, m.subject, m.body);
      log[key] = d_(today); created.push(d.getId());
    }
  });
  var elec = electricityTasks_(active, today, log, mode);
  var digest = digest_(items, warnings, today);
  if (elec.length) digest.body = 'Задачи «счёт за электричество» сегодня:\n• ' + elec.join('\n• ') + '\n\n' + digest.body;
  if (mode === 'draft' && (items.length || warnings.length || elec.length)) {
    GmailApp.createDraft(c.digestTo, digest.subject, digest.body);
    PropertiesService.getScriptProperties().setProperty('SENT_LOG', JSON.stringify(log));
  }
  Logger.log('[' + mode + '] ' + digest.subject + '\n' + digest.body);
  if (mode === 'dry') items.forEach(function (it) { if (it.type !== 'DEPOSIT_UNPAID') { var m = tenantMail_(it); Logger.log('--- would draft to ' + (it.t.email || '(no email)') + ': ' + m.subject + '\n' + m.body); } });
  return {mode: mode, items: items.length, warnings: warnings.length, draftsCreated: created.length};
}

function tenantMail_(it) {
  var t = it.t, who = t.contact || t.tenant, room = [t.floor, t.room].filter(String).join(', ');
  if (it.type === 'PAYMENT') return {
    subject: 'Place Coworking — rent reminder (' + room + ')',
    body: 'Dear ' + who + ',\n\nThis is a friendly reminder that the rent for ' + room + (t.rent ? ' (' + t.rent + ' THB)' : '') +
      ' is due on ' + d_(t.nextPay) + (it.days === 0 ? ' (today)' : ' (in ' + it.days + ' days)') + '.\n' +
      'If you have already paid, please ignore this message or send us the transfer slip.\n\nThank you,\nPlace Coworking'
  };
  return {
    subject: 'Place Coworking — your office contract ends on ' + d_(t.end),
    body: 'Dear ' + who + ',\n\nYour contract for ' + room + ' ends on ' + d_(t.end) + ' (in ' + it.days + ' days).\n' +
      'Would you like to extend it? Please reply to this email and we will prepare the renewal. ' +
      'If you plan to move out, please let us know so we can arrange the key return and the deposit.\n\nThank you,\nPlace Coworking'
  };
}

function digest_(items, warnings, today) {
  var label = {PAYMENT: 'Payment due', CONTRACT_END: 'Contract ends', DEPOSIT_UNPAID: 'Deposit NOT paid'};
  var lines = items.map(function (it) {
    var t = it.t;
    return '• ' + label[it.type] + (it.days !== null ? ' in ' + it.days + ' d' : '') + ': ' + t.tenant + ' — ' + [t.floor, t.room].join(' ') +
      (it.type === 'PAYMENT' ? ', ' + d_(t.nextPay) + ', ' + t.rent + ' THB' : '') + (it.type === 'CONTRACT_END' ? ', ' + d_(t.end) : '') +
      (it.type === 'DEPOSIT_UNPAID' ? ', ' + t.deposit + ' THB' : '') + (it.already ? ' (reminder already drafted)' : '');
  });
  return {
    subject: 'Offices digest ' + d_(today) + ': ' + items.length + ' reminders, ' + warnings.length + ' warnings',
    body: (lines.length ? lines.join('\n') : 'No reminders today.') + (warnings.length ? '\n\nWarnings:\n• ' + warnings.join('\n• ') : '') +
      '\n\n(Drafts only. Review in Gmail Drafts and send manually.)'
  };
}

// Assignee of the electricity-bill task: Lena (approved role, George 29.09 19:40)
var ELEC_ASSIGNEE = 'Lena';

/** Rent-month start today? -> tech task. log = SENT_LOG object (dedupe key ELEC|row|yyyy-MM). */
function electricityTasks_(active, today, log, runMode) {
  var p = PropertiesService.getScriptProperties();
  // writes only when the whole run is in draft mode AND ELEC_TASK_MODE=issues; dryRun() never writes
  var mode = runMode === 'draft' ? (p.getProperty('ELEC_TASK_MODE') || 'dry') : 'dry';
  var out = [];
  active.forEach(function (t) {
    if (!t.start || (t.end && t.end < today) || t.start > today) return;
    var dim = new Date(today.getFullYear(), today.getMonth() + 1, 0).getDate();
    var due = Math.min(t.start.getDate(), dim);
    if (today.getDate() !== due) return;
    var office = [t.floor ? t.floor + ' эт.' : '', t.room].filter(String).join(' ');
    var text = 'выставить счёт за электричество: ' + office + ', ' + t.tenant;
    var key = 'ELEC|' + t.row + '|' + Utilities.formatDate(today, TZ, 'yyyy-MM');
    if (log[key]) return;
    out.push(text + ' → ' + ELEC_ASSIGNEE);
    if (mode === 'issues') {
      var id = p.getProperty('ISSUES_SHEET_ID');
      var sh = id && SpreadsheetApp.openById(id).getSheetByName('Issues');
      if (!sh) { Logger.log('ELEC: no Issues tab / ISSUES_SHEET_ID -> dry'); Logger.log('[elec dry] ' + text); return; }
      var now = Utilities.formatDate(new Date(), TZ, 'yyyy-MM-dd HH:mm');
      // same columns as issues-log.gs ISSUES_HEAD (last = assignee)
      sh.appendRow(['elec:' + t.row + ':' + Utilities.formatDate(today, TZ, 'yyyy-MM'), now, t.floor, 'Place Ops (auto)', text, 'open', '', now, '', '', '', '', ELEC_ASSIGNEE]);
      log[key] = d_(today);
      PropertiesService.getScriptProperties().setProperty('SENT_LOG', JSON.stringify(log));
    } else Logger.log('[elec dry] ' + text + ' (assignee: ' + ELEC_ASSIGNEE + ')');
  });
  return out;
}

// ---------- helpers ----------
function today_() { var o = PropertiesService.getScriptProperties().getProperty('TODAY_OVERRIDE'); var s = (o && /^\d{4}-\d{2}-\d{2}$/.test(o) ? o : Utilities.formatDate(new Date(), TZ, 'yyyy-MM-dd')).split('-'); return new Date(Number(s[0]), Number(s[1]) - 1, Number(s[2])); }
function diffDays_(a, b) { return Math.round((b - a) / 86400000); }
function d_(d) { return d ? Utilities.formatDate(d, TZ, 'dd.MM.yyyy') : ''; }
function overlap_(a, b) { var far = new Date(2100, 0, 1), s1 = a.start || new Date(2000, 0, 1), s2 = b.start || new Date(2000, 0, 1); return s1 <= (b.end || far) && s2 <= (a.end || far); }
/** Date cell, or text dd.mm.yy / dd/mm/yyyy / yyyy-mm-dd. */
function date_(v) {
  if (v instanceof Date && !isNaN(v)) return new Date(v.getFullYear(), v.getMonth(), v.getDate());
  var s = String(v || '').trim(), m;
  if ((m = s.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/))) return new Date(+m[1], +m[2] - 1, +m[3]);
  if ((m = s.match(/^(\d{1,2})[./-](\d{1,2})[./-](\d{2,4})$/))) return new Date(m[3].length === 2 ? 2000 + +m[3] : +m[3], +m[2] - 1, +m[1]);
  return null;
}

return {dryRun: dryRun, run_: run_, resetSentLog: resetSentLog};
})(T_props_('ST6'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 20-IssuesLog.gs =====
/** GENERATED by build-test-project.sh from issues-log.gs — do not edit here. Module ISS (TEST sandbox). */
var ISS = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {
var SHEET_ID = T_IDS.inbox; // TEST: Place Inbox TEST, never the live bridge sheet
/**
 * Place Coworking — 2.1.5 / 10.1 Breakdown & issue log. DRAFT TEMPLATE, NOT DEPLOYED.
 *
 * Plugs into the TG bridge (docs/ops/tg-bridge/Code.template.gs). Every new
 * top-level message in the «Тех вопросы» chat becomes a row in tab «Issues»
 * (same Place Inbox spreadsheet as «Заказы»). A reply to that message with a
 * "done" word (готово / починил / fixed / เสร็จ / แก้แล้ว / ซ่อมแล้ว …) closes it;
 * any other reply marks it in_progress and is kept as the last note.
 * issuesDigest_() builds the text for the existing 10:07 (open list) and
 * 23:10 (closed today + still open) runs. No new Lead runs, no TG sends here.
 *
 * Hook (one line in poll(), after the orders hook):
 *   if (ISSUES_CHAT_RE.test(chat) && !(u.edited_message)) try { issuesHandle_(issuesSheet_(), m, text, name); } catch (e) { Logger.log('ISSUES_ERR ' + e); }
 *
 * SAFETY: ISSUES_MODE (Script Property) defaults to 'dry' = log only, no sheet
 * writes. 'live' writes to the «Issues» tab — only after George OK.
 */

var ISSUES_CHAT_RE = /тех\s*вопрос/i;
var ISSUES_TAB = 'Issues';
var ISSUES_HEAD = ['issue_id', 'opened_at_ict', 'floor', 'reporter', 'text', 'status', 'last_note', 'last_update_ict', 'closed_at_ict', 'closed_by', 'tg_chat_id', 'tg_message_id', 'assignee'];
var DONE_RE = /(готово|сделано|сделал|починил|починили|исправил|решено|закрыто|fixed|done|resolved|เสร็จ|แก้แล้ว|ซ่อมแล้ว|เรียบร้อย)/i;
var BOT_RE = /placeleadbot/i;

function issuesSheet_() {
  var ss = SpreadsheetApp.openById(SHEET_ID);
  var sh = ss.getSheetByName(ISSUES_TAB);
  if (!sh) {
    if (issuesMode_() !== 'live') return null;
    sh = ss.insertSheet(ISSUES_TAB);
    sh.appendRow(ISSUES_HEAD);
  }
  return sh;
}

function issuesMode_() { return PropertiesService.getScriptProperties().getProperty('ISSUES_MODE') || 'dry'; }

function issuesHandle_(sh, m, text, sender) {
  var f = m.from || {};
  if (BOT_RE.test(f.username || '')) return 'skip-bot';
  var when = Utilities.formatDate(new Date(m.date * 1000), 'Asia/Bangkok', 'yyyy-MM-dd HH:mm');
  var live = issuesMode_() === 'live' && sh;
  var rows = sh ? sh.getDataRange().getValues() : [ISSUES_HEAD];
  var col = {}; ISSUES_HEAD.forEach(function (h, i) { col[h] = i; });
  var replyTo = m.reply_to_message ? String(m.reply_to_message.message_id) : null;
  if (replyTo) {
    for (var r = 1; r < rows.length; r++) {
      if (String(rows[r][col.tg_message_id]) === replyTo && String(rows[r][col.tg_chat_id]) === String(m.chat.id)) {
        var row = rows[r].slice();
        row[col.last_note] = (sender + ': ' + text).slice(0, 500);
        row[col.last_update_ict] = when;
        if (DONE_RE.test(text)) { row[col.status] = 'closed'; row[col.closed_at_ict] = when; row[col.closed_by] = sender; }
        else if (row[col.status] === 'open') row[col.status] = 'in_progress';
        if (live) sh.getRange(r + 1, 1, 1, ISSUES_HEAD.length).setValues([row]);
        else Logger.log('[issues dry] update row ' + (r + 1) + ': ' + JSON.stringify(row));
        return row[col.status];
      }
    }
    return 'reply-untracked';
  }
  var floor = typeof parseFloor_ === 'function' ? parseFloor_(text) : issuesFloor_(text);
  var newRow = [m.chat.id + ':' + m.message_id, when, floor, sender, text.slice(0, 1000), 'open', '', when, '', '', String(m.chat.id), String(m.message_id), ''];
  if (live) sh.appendRow(newRow); else Logger.log('[issues dry] new: ' + JSON.stringify(newRow));
  return 'open';
}

function issuesFloor_(text) {
  var m = String(text).match(/(\d)\s*(?:этаж|эт\.?|floor|fl\.?|ชั้น)|(?:этаж|floor|ชั้น)\s*(\d)/i);
  return m ? (m[1] || m[2]) : '';
}

/** kind: 'morning' (10:07) | 'evening' (23:10). Returns text for the Lead report. */
function issuesDigest_(kind, now) {
  var sh = SpreadsheetApp.openById(SHEET_ID).getSheetByName(ISSUES_TAB);
  if (!sh) return 'Issues: вкладки нет (ещё не запущено).';
  var rows = sh.getDataRange().getValues(), col = {}; ISSUES_HEAD.forEach(function (h, i) { col[h] = i; });
  var today = Utilities.formatDate(now || new Date(), 'Asia/Bangkok', 'yyyy-MM-dd');
  var nowMs = (now || new Date()).getTime();
  var open = [], closedToday = [];
  for (var r = 1; r < rows.length; r++) {
    var x = rows[r], st = x[col.status];
    var line = (x[col.floor] ? x[col.floor] + ' эт. ' : '') + String(x[col.text]).slice(0, 80);
    if (st === 'closed') { if (String(x[col.closed_at_ict]).indexOf(today) === 0) closedToday.push('✅ ' + line + ' (' + x[col.closed_by] + ')'); }
    else {
      var opened = new Date(String(x[col.opened_at_ict]).replace(' ', 'T') + ':00+07:00').getTime();
      var days = Math.floor((nowMs - opened) / 86400000);
      open.push({d: days, s: (st === 'in_progress' ? '🔧 ' : '🔴 ') + line + ' (' + (days ? days + ' дн.' : 'сегодня') + ')'});
    }
  }
  open.sort(function (a, b) { return b.d - a.d; });
  var txt = 'Поломки: открыто ' + open.length + (kind === 'evening' ? ', закрыто сегодня ' + closedToday.length : '') + '\n' + open.map(function (o) { return o.s; }).join('\n');
  if (kind === 'evening' && closedToday.length) txt += '\n' + closedToday.join('\n');
  return txt;
}

/** Offline test with fake updates. In dry mode only logs. */
function dryRunIssues() {
  var chat = {id: -100123, title: 'Тех вопросы', type: 'supergroup'}, t = 1790700000;
  var log = [];
  log.push(issuesHandle_(null, {chat: chat, message_id: 501, date: t, from: {username: 'som'}}, 'Кондиционер на 3 этаже течёт', 'Som'));
  log.push(issuesHandle_(null, {chat: chat, message_id: 502, date: t + 60, from: {username: 'tangmo'}}, 'ชั้น 1 ไฟดับ 2 ดวง', 'Tangmo'));
  Logger.log(JSON.stringify(log));
  return log;
}

return {issuesSheet_: issuesSheet_, issuesHandle_: issuesHandle_, issuesDigest_: issuesDigest_, ISSUES_CHAT_RE: ISSUES_CHAT_RE};
})(T_props_('ISS'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 30-Bookings.gs =====
/** GENERATED by build-test-project.sh from bookings-today.gs — do not edit here. Module BKG (TEST sandbox). */
var BKG = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — G-5 «Брони на сегодня» из Events and booking. DRAFT TEMPLATE, NOT DEPLOYED.
 * READ-ONLY: never writes to the sheet, never sends. Returns text for the existing 10:07 run.
 *
 * Sheet layout (checked read-only 29.09.2026): each tab = one space; row 4 = "Time" + one column
 * per day ("Mon 28/10" or "ПН 11.03"), month marker columns like "Jan\n2025" / "September\n2026"
 * give the year; column A = time slots (09:00, 09:30 …); a booking = any non-empty cell.
 * FINDING 29.09: the «Meeting room» grid ends at Wed 30/09/2026 (+ an "October 2026" marker) —
 * no columns for October yet.
 *
 * Script Properties (optional): EVENTS_SHEET_ID, BOOKING_TABS (JSON list), HEADER_ROW=4, LOOKAHEAD_DAYS=14
 */
var BK_TZ = 'Asia/Bangkok';
var BK_ID = '1BSwm4sY-ksXjFNEEsAdyiWmUDzgbQlJpL_dh9JIdZAc';
var BK_TABS = ['Meeting room', '1 floor', '4 floor', 'ART Room ', 'Workshop room', 'Office room-4 (GREEN)', '6 floor'];
var BK_MONTHS = {jan: 0, feb: 1, mar: 2, apr: 3, may: 4, jun: 5, jul: 6, aug: 7, sep: 8, oct: 9, nov: 10, dec: 11};

function dryRunBookings() { var t = bookingsToday_(new Date()); Logger.log(t); return t; }

function bookingsToday_(now) {
  var p = PropertiesService.getScriptProperties();
  var ss = SpreadsheetApp.openById(p.getProperty('EVENTS_SHEET_ID') || BK_ID);
  var tabs = JSON.parse(p.getProperty('BOOKING_TABS') || JSON.stringify(BK_TABS));
  var hr = Number(p.getProperty('HEADER_ROW') || 4), look = Number(p.getProperty('LOOKAHEAD_DAYS') || 14);
  var s = Utilities.formatDate(now, BK_TZ, 'yyyy-MM-dd').split('-');
  var today = new Date(+s[0], +s[1] - 1, +s[2]);
  var horizon = new Date(today.getFullYear(), today.getMonth(), today.getDate() + look);
  var lines = [], warn = [];
  tabs.forEach(function (name) {
    var sh = ss.getSheetByName(name);
    if (!sh) { warn.push('нет вкладки ' + name); return; }
    var disp = sh.getDataRange().getDisplayValues();
    if (disp.length < hr) return;
    var cols = bkDateCols_(disp[hr - 1], today.getFullYear());
    var key = bkKey_(today), col = cols.map[key];
    if (cols.last && cols.last < horizon) warn.push(name.trim() + ': сетка заканчивается ' + Utilities.formatDate(cols.last, BK_TZ, 'dd.MM.yyyy') + ', дальше брони некуда записать');
    if (col === undefined) return;
    var items = [];
    for (var r = hr; r < disp.length; r++) {
      var v = String(disp[r][col] || '').trim();
      if (v) items.push((String(disp[r][0] || '').trim() || '?') + ' ' + v.replace(/\s+/g, ' ').slice(0, 120));
    }
    if (items.length) lines.push('• ' + name.trim() + ':\n   ' + items.join('\n   '));
  });
  return 'Брони на сегодня (' + Utilities.formatDate(today, BK_TZ, 'dd.MM') + '):\n' + (lines.length ? lines.join('\n') : 'нет') +
    (warn.length ? '\n⚠️ ' + warn.join('\n⚠️ ') : '');
}

/** Header row -> {map: {yyyy-mm-dd: colIndex}, last: Date}. Year from month markers; rollover Dec->Jan. */
function bkDateCols_(row, fallbackYear) {
  var map = {}, year = null, lastMonth = null, last = null;
  for (var j = 1; j < row.length; j++) {
    var c = String(row[j] || '').trim();
    var mk = c.match(/^([A-Za-z]+)\s*\n?\s*(\d{4})$/);
    if (mk) { year = +mk[2]; continue; }
    var m = c.match(/(\d{1,2})[\/.](\d{1,2})$/);
    if (!m) continue;
    var d = +m[1], mo = +m[2] - 1;
    if (year === null) year = fallbackYear - 2; // first columns before any marker (e.g. Oct 2024)
    if (lastMonth !== null && mo < lastMonth && !mk) { if (lastMonth === 11 && mo === 0) year++; }
    lastMonth = mo;
    var dt = new Date(year, mo, d);
    map[bkKey_(dt)] = j; last = dt;
  }
  return {map: map, last: last};
}
function bkKey_(d) { return d.getFullYear() + '-' + (d.getMonth() + 1) + '-' + d.getDate(); }

return {bookingsToday_: bookingsToday_, dryRunBookings: dryRunBookings};
})(T_props_('BKG'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 40-Keyholders.gs =====
/** GENERATED by build-test-project.sh from keyholders-247.gs — do not edit here. Module KH (TEST sandbox). */
var KH = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — C8 «Ключи 24/7» для чек-листа закрытия 22:30. DRAFT TEMPLATE, NOT DEPLOYED.
 * READ-ONLY: never writes, never sends. Returns text for the existing close-checklist run.
 *
 * Needs 3 columns in Resident info «Лист1» (proposal D-DRAFTS.md §2; added only in the TEST copy):
 *   «24/7 (Y/N)» · «Key # / card #» · «Key deposit paid (date, ฿)»
 * Active = 24/7 = Y and Finish >= today (Finish is dd.mm or dd.mm.yy[yy]; dd.mm = current year).
 * Script Properties (optional): RESIDENT_SHEET_ID, KEY_TAB='Лист1'.
 */
var KH_TZ = 'Asia/Bangkok';
var KH_ID = '1Rzz9CKQYHwgZ8BPtrTxxUwFdphphSivSJkkTwFC8wo4';
var KH_HEAD = {name: 'name', finish: 'finish', floor: 'floor access', flag: '24/7 (y/n)', key: 'key # / card #', dep: 'key deposit paid (date, ฿)'};

function dryRunKeyholders() { var t = keyholders247_(new Date()); Logger.log(t); return t; }

function keyholders247_(now) {
  var p = PropertiesService.getScriptProperties();
  var sh = SpreadsheetApp.openById(p.getProperty('RESIDENT_SHEET_ID') || KH_ID).getSheetByName(p.getProperty('KEY_TAB') || 'Лист1');
  if (!sh) return '24/7: нет вкладки';
  var v = sh.getDataRange().getDisplayValues();
  var head = v[0].map(function (h) { return String(h).trim().toLowerCase(); }), ix = {};
  Object.keys(KH_HEAD).forEach(function (k) { ix[k] = head.indexOf(KH_HEAD[k]); });
  if (ix.flag < 0) return '24/7: колонок 24/7 нет (нужна правка Resident info по OK George)';
  var s = Utilities.formatDate(now, KH_TZ, 'yyyy-MM-dd').split('-'), today = new Date(+s[0], +s[1] - 1, +s[2]);
  var act = [], warn = [];
  for (var r = 1; r < v.length; r++) {
    if (!/^y/i.test(String(v[r][ix.flag]).trim())) continue;
    var name = String(v[r][ix.name] || '').trim(), fin = khDate_(v[r][ix.finish], today.getFullYear());
    var key = ix.key >= 0 ? String(v[r][ix.key]).trim() : '', dep = ix.dep >= 0 ? String(v[r][ix.dep]).trim() : '';
    if (!fin) { warn.push('стр. ' + (r + 1) + ' ' + name + ': нет даты Finish'); continue; }
    if (fin < today) { if (key) warn.push('стр. ' + (r + 1) + ' ' + name + ': 24/7 истёк ' + Utilities.formatDate(fin, KH_TZ, 'dd.MM') + ', ключ ' + key + ' не возвращён?'); continue; }
    act.push('• ' + name + (key ? ' — ключ ' + key : ' — ключ не указан') + ' (до ' + Utilities.formatDate(fin, KH_TZ, 'dd.MM') + ')' + (dep ? '' : ' ⚠️ депозит за ключ не отмечен'));
  }
  return 'Ключи 24/7: активных ' + act.length + '\n' + act.join('\n') + (warn.length ? '\n⚠️ ' + warn.join('\n⚠️ ') : '');
}
function khDate_(x, y) {
  var m = String(x || '').trim().match(/^(\d{1,2})[./](\d{1,2})(?:[./](\d{2,4}))?$/);
  if (!m) return null;
  var yy = m[3] ? (m[3].length === 2 ? 2000 + +m[3] : +m[3]) : y;
  return new Date(yy, +m[2] - 1, +m[1]);
}

return {keyholders247_: keyholders247_};
})(T_props_('KH'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 50-Timesheet.gs =====
/** GENERATED by build-test-project.sh from stage5-timesheet.gs — do not edit here. Module ST5 (TEST sandbox). */
var ST5 = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — Stage 5 (7.1.14 Timesheet). DRAFT TEMPLATE, NOT DEPLOYED.
 *
 * Reads a Schedule-26-style sheet (one tab per month: Jan..Dec;
 * columns: Position | Name | day1..dayN | Total Hrs.), computes hours per staff
 * member and builds a timesheet email for the accountant.
 *
 * PAYROLL RULES (Aiz 30.09.2026, kb/ops/payroll-rules.md b3a8c49):
 *  - payroll period = calendar month (1st .. last day);
 *  - the timesheet goes to the accountant on the 28th (CUTOFF_DAY);
 *  - leave taken after the 28th is deducted in NEXT month's payroll.
 * So a run on the 28th covers the current month: days 1..28 are the timesheet table; days 29..end (not yet worked)
 * are listed as «after cutoff → next month adjustments» (planned shifts / leave), and the previous month's
 * days 29..end are listed as «adjustments from previous month» (leave actually taken after last cutoff).
 *
 * SAFETY:
 *  - The script NEVER sends email. There is no GmailApp.sendEmail / MailApp call.
 *  - dryRun() only writes to the log.
 *  - createTimesheetDraft() creates a Gmail DRAFT only, and only when the Script
 *    Property DRAFT_ENABLED = 'true'. A human reviews and sends it manually.
 *  - Read-only access to the sheet (no writes).
 *
 * SETUP (after George OK; run from info@placecoworking.com):
 *  1. Schedule 26 must be owned by / shared with info@ (right now it is owned
 *     by Aiz's personal gmail and info@ has view only; view is enough to read,
 *     but ownership must move before 30.09).
 *  1b. Project Settings -> Time zone = (GMT+07:00) Bangkok.
 *  2. Project Settings -> Script Properties (all optional except the addresses):
 *     SCHEDULE_SHEET_ID   default 1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc (Schedule 26)
 *     SHEET_YEAR          year of SCHEDULE_SHEET_ID, default 2026
 *     SHEET_ID_BY_YEAR    JSON, e.g. {"2025":"<id>","2027":"<id>"} for periods crossing a year
 *     TAB_NAMES           JSON array of 12 tab names, default ["Jan",...,"Dec"]
 *     POSITION_COL        default A
 *     NAME_COL            default B
 *     FIRST_DAY_COL       default '' = auto-detect the row with day numbers 1..31
 *     DAY_HEADER_ROW      default '' = auto-detect (scans first HEADER_SCAN_ROWS rows)
 *     HEADER_SCAN_ROWS    default 10
 *     PERIOD_MODE         'month' (default): calendar month; run on/after CUTOFF_DAY -> current month, before -> previous month
 *                         'custom': PERIOD_START_DAY (21) .. PERIOD_END_DAY (20), the old 21–20 scheme
 *     CUTOFF_DAY          default 28 (timesheet sent to the accountant; later leave -> next month)
 *     PERIOD_FROM / PERIOD_TO  optional explicit ISO dates (yyyy-mm-dd), override the above (cutoff = PERIOD_TO)
 *     BREAK_HOURS         unpaid break deducted per shift, default 0 (to confirm)
 *     EXCLUDE_NAMES       comma list of names to skip (e.g. owners)
 *     ACCOUNTANT_TO       accountant address (NOT stored in repo)
 *     ACCOUNTANT_CC       cc address(es), comma separated (NOT stored in repo)
 *     GREETING            default 'Dear Khun Pat,' (new accountant, 30.09.2026)
 *     SUBJECT_PREFIX      default 'Place Coworking — timesheet'
 *     DRAFT_ENABLED       'true' to allow createTimesheetDraft(); anything else = dry
 */

var TZ = 'Asia/Bangkok';
var DEFAULT_SHEET_ID = '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc';
var DEFAULT_TABS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

// Non-shift marks seen in Schedule 26. Order matters: first match wins.
var MARKS = [
  {code: 'UNPAID', re: /(leave\s*with\s*out\s*money|without\s*money|unpaid|ลาไม่รับเงิน)/i},
  {code: 'SICK',   re: /(sick|ป่วย)/i},
  {code: 'ANNUAL', re: /(annual|พักร้อน)/i},
  {code: 'DOCTOR', re: /(doctor)/i},
  {code: 'OFF',    re: /^(off|day\s*off|หยุด|-|x)$/i}
];

// ---------- entry points ----------

/** Log-only run: computes the period, hours and the email text. Nothing is created. */
function dryRun() {
  var res = buildTimesheet_(cfg_());
  Logger.log(res.subject);
  Logger.log(res.text);
  if (res.warnings.length) Logger.log('WARNINGS:\n' + res.warnings.join('\n'));
  return res;
}

/** Creates a Gmail DRAFT for the accountant (never sends). Requires DRAFT_ENABLED=true. */
function createTimesheetDraft() {
  var c = cfg_();
  var res = buildTimesheet_(c);
  if (c.draftEnabled !== 'true') {
    Logger.log('DRAFT_ENABLED is not "true" -> dry run only.\n' + res.subject + '\n' + res.text);
    return 'DRY';
  }
  if (!c.to) throw new Error('ACCOUNTANT_TO is empty');
  var csv = Utilities.newBlob(res.csv, 'text/csv', 'timesheet_' + res.fromIso + '_' + res.toIso + '.csv');
  var d = GmailApp.createDraft(c.to, res.subject, res.text, {cc: c.cc || '', htmlBody: res.html, attachments: [csv]});
  Logger.log('DRAFT_CREATED ' + d.getId() + ' — review in Gmail Drafts and send manually.');
  return d.getId();
}

// ---------- core ----------

function cfg_() {
  var p = PropertiesService.getScriptProperties();
  var g = function (k, d) { var v = p.getProperty(k); return (v === null || v === '') ? d : v; };
  return {
    sheetId: g('SCHEDULE_SHEET_ID', DEFAULT_SHEET_ID),
    sheetYear: Number(g('SHEET_YEAR', '2026')),
    sheetByYear: JSON.parse(g('SHEET_ID_BY_YEAR', '{}')),
    tabs: JSON.parse(g('TAB_NAMES', JSON.stringify(DEFAULT_TABS))),
    posCol: colIdx_(g('POSITION_COL', 'A')),
    nameCol: colIdx_(g('NAME_COL', 'B')),
    firstDayCol: g('FIRST_DAY_COL', '') ? colIdx_(g('FIRST_DAY_COL', '')) : null,
    dayHeaderRow: g('DAY_HEADER_ROW', '') ? Number(g('DAY_HEADER_ROW', '')) : null,
    scanRows: Number(g('HEADER_SCAN_ROWS', '10')),
    startDay: Number(g('PERIOD_START_DAY', '21')),
    endDay: Number(g('PERIOD_END_DAY', '20')),
    from: g('PERIOD_FROM', ''), to_: g('PERIOD_TO', ''),
    mode: g('PERIOD_MODE', 'month'), cutoff: Number(g('CUTOFF_DAY', '28')),
    breakHours: Number(g('BREAK_HOURS', '0')),
    exclude: g('EXCLUDE_NAMES', '').split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(String),
    to: g('ACCOUNTANT_TO', ''), cc: g('ACCOUNTANT_CC', ''),
    greeting: g('GREETING', 'Dear Khun Pat,'),
    prefix: g('SUBJECT_PREFIX', 'Place Coworking — timesheet'),
    draftEnabled: g('DRAFT_ENABLED', 'false')
  };
}

/** Payroll period. Default (PERIOD_MODE=month): calendar month; on/after the cutoff day -> current month, else previous.
 *  Returns {from, to, cut}: the table covers from..cut; cut+1..to = after cutoff (next month adjustments). */
function period_(c) {
  if (c.from && c.to_) { var t = isoDate_(c.to_); return {from: isoDate_(c.from), to: t, cut: t}; }
  var now = new Date(Utilities.formatDate(new Date(), TZ, "yyyy-MM-dd'T'00:00:00"));
  var y = now.getFullYear(), m = now.getMonth();
  if (c.mode !== 'custom') {
    if (now.getDate() < c.cutoff) m -= 1;
    var first = new Date(y, m, 1), last = new Date(y, m + 1, 0);
    var cut = new Date(first.getFullYear(), first.getMonth(), Math.min(c.cutoff, last.getDate()));
    return {from: first, to: last, cut: cut};
  }
  if (c.startDay === 1) { var f = new Date(y, m - 1, 1), l = new Date(y, m, 0); return {from: f, to: l, cut: l}; }
  // old scheme: period ends on endDay of month M; take the latest endDay that is < today
  var end = new Date(y, m, c.endDay);
  if (end >= now) end = new Date(y, m - 1, c.endDay);
  var from = new Date(end.getFullYear(), end.getMonth() - 1, c.startDay);
  return {from: from, to: end, cut: end};
}

/** Reads Schedule 26 for days from..to (may span months). */
function collect_(c, from, to, warnings) {
  var people = {}, order = [], byMonth = {};
  for (var d = new Date(from); d <= to; d.setDate(d.getDate() + 1)) {
    var key = d.getFullYear() + '-' + d.getMonth();
    (byMonth[key] = byMonth[key] || {y: d.getFullYear(), m: d.getMonth(), days: []}).days.push(d.getDate());
  }
  Object.keys(byMonth).forEach(function (k) {
    var bm = byMonth[k];
    var id = c.sheetByYear[String(bm.y)] || (bm.y === c.sheetYear ? c.sheetId : null);
    if (!id) { warnings.push('No sheet for year ' + bm.y + ' (set SHEET_ID_BY_YEAR); days skipped: ' + bm.days.join(',')); return; }
    var sh = SpreadsheetApp.openById(id).getSheetByName(c.tabs[bm.m]);
    if (!sh) { warnings.push('Tab "' + c.tabs[bm.m] + '" not found in ' + id); return; }
    readMonth_(sh, bm, c, people, order, warnings);
  });
  return {people: people, order: order};
}

/** One line per person with leave / planned shifts in a side period (after cutoff, or previous month's tail). */
function sideLines_(res, withShifts) {
  var out = [];
  res.order.forEach(function (k) {
    var p = res.people[k], parts = [];
    if (withShifts && p.shifts) parts.push(p.shifts + ' shift(s) planned');
    if (p.ANNUAL) parts.push('annual ' + p.ANNUAL);
    if (p.SICK) parts.push('sick ' + p.SICK);
    if (p.UNPAID) parts.push('unpaid ' + p.UNPAID);
    if (p.DOCTOR) parts.push('doctor ' + p.DOCTOR);
    if (p.unknown.length) parts.push('unrecognised: ' + p.unknown.join('; '));
    if (parts.length) out.push(p.name + ': ' + parts.join(', '));
  });
  return out;
}

function buildTimesheet_(c) {
  var per = period_(c), warnings = [];
  var main = collect_(c, per.from, per.cut, warnings), people = main.people, order = main.order;
  var afterFrom = new Date(per.cut.getFullYear(), per.cut.getMonth(), per.cut.getDate() + 1);
  var after = afterFrom <= per.to ? collect_(c, afterFrom, per.to, warnings) : null;
  var prevEnd = new Date(per.from.getFullYear(), per.from.getMonth(), 0), prevFrom = new Date(prevEnd.getFullYear(), prevEnd.getMonth(), c.cutoff + 1);
  var prev = (c.mode !== 'custom' && !(c.from && c.to_) && prevFrom <= prevEnd) ? collect_(c, prevFrom, prevEnd, warnings) : null;
  var D = function (x) { return fmt_(x, 'dd.MM.yyyy'); };
  var afterLines = after ? sideLines_(after, true) : [], prevLines = prev ? sideLines_(prev, false) : [];
  var afterTitle = after ? 'After cutoff ' + fmt_(afterFrom, 'dd.MM') + '–' + D(per.to) + ' (not yet worked → next month adjustments):' : '';
  var prevTitle = prev ? 'Adjustments from previous month ' + fmt_(prevFrom, 'dd.MM') + '–' + D(prevEnd) + ' (leave after last cutoff):' : '';

  var fromIso = fmt_(per.from, 'yyyy-MM-dd'), toIso = fmt_(per.to, 'yyyy-MM-dd');
  var head = ['Position', 'Name', 'Shifts', 'Hours', 'Annual leave (days)', 'Sick (days)', 'Unpaid leave (days)', 'Doctor', 'Unrecognised cells'];
  var rows = order.map(function (k) {
    var p = people[k];
    return [p.position, p.name, p.shifts, round2_(p.hours), p.ANNUAL, p.SICK, p.UNPAID, p.DOCTOR, p.unknown.join('; ')];
  });
  var range = D(per.from) + '–' + D(per.to) + (per.cut < per.to ? ' (counted to ' + D(per.cut) + ')' : '');
  var subject = c.prefix + ' ' + D(per.from) + '–' + D(per.to);
  var sections = (after ? '\n\n' + afterTitle + '\n' + (afterLines.length ? afterLines.map(function (l) { return '• ' + l; }).join('\n') : '• none') : '') +
    (prev ? '\n\n' + prevTitle + '\n' + (prevLines.length ? prevLines.map(function (l) { return '• ' + l; }).join('\n') : '• none') : '');
  var text = c.greeting + '\n\nPlease find the staff timesheet for the period ' + range + ' (from Schedule 26).\n\n' +
    [head.join(' | ')].concat(rows.map(function (r) { return r.join(' | '); })).join('\n') + sections +
    '\n\nUnpaid leave days are listed for the deduction (monthly salary / 30 per day; SSO 5% is calculated after the deduction, cap 875). Leave after the ' + c.cutoff + 'th is deducted in the next month.' +
    '\nThe same table is attached as CSV. Please let us know if anything needs to be corrected.\n\nBest regards,\nPlace Coworking';
  var htmlList = function (title, lines) { return '<p><b>' + esc_(title) + '</b></p><ul>' + (lines.length ? lines : ['none']).map(function (l) { return '<li>' + esc_(l) + '</li>'; }).join('') + '</ul>'; };
  var html = '<p>' + esc_(c.greeting) + '</p><p>Please find the staff timesheet for the period <b>' + esc_(range) + '</b> (from Schedule 26).</p>' +
    '<table border="1" cellpadding="4" style="border-collapse:collapse"><tr>' + head.map(function (h) { return '<th>' + esc_(h) + '</th>'; }).join('') + '</tr>' +
    rows.map(function (r) { return '<tr>' + r.map(function (v) { return '<td>' + esc_(String(v)) + '</td>'; }).join('') + '</tr>'; }).join('') + '</table>' +
    (after ? htmlList(afterTitle, afterLines) : '') + (prev ? htmlList(prevTitle, prevLines) : '') +
    '<p>Unpaid leave days are listed for the deduction (monthly salary / 30 per day; SSO 5% is calculated after the deduction, cap 875). Leave after the ' + c.cutoff + 'th is deducted in the next month.<br>The same table is attached as CSV. Please let us know if anything needs to be corrected.</p><p>Best regards,<br>Place Coworking</p>';
  var csvRows = [head].concat(rows);
  if (after) { csvRows.push([]); csvRows.push([afterTitle]); afterLines.forEach(function (l) { csvRows.push(['', l]); }); }
  if (prev) { csvRows.push([]); csvRows.push([prevTitle]); prevLines.forEach(function (l) { csvRows.push(['', l]); }); }
  var csv = csvRows.map(function (r) { return r.map(csvCell_).join(','); }).join('\n');
  return {subject: subject, text: text, html: html, csv: csv, rows: rows, warnings: warnings, fromIso: fromIso, toIso: toIso,
    cutIso: fmt_(per.cut, 'yyyy-MM-dd'), afterCutoff: afterLines, prevAdjustments: prevLines};
}

function readMonth_(sh, bm, c, people, order, warnings) {
  var vals = sh.getDataRange().getValues();
  var disp = sh.getDataRange().getDisplayValues();
  var hdr = findDayHeader_(vals, c);
  if (!hdr) { warnings.push(sh.getName() + ': day header row (1..31) not found; set DAY_HEADER_ROW / FIRST_DAY_COL'); return; }
  var lastPos = '';
  for (var r = hdr.row + 1; r < vals.length; r++) {
    var name = String(disp[r][c.nameCol] || '').trim();
    var pos = String(disp[r][c.posCol] || '').trim();
    if (pos) lastPos = pos;
    if (!name || /^name$/i.test(name) || /total/i.test(name)) continue;
    if (c.exclude.indexOf(name.toLowerCase()) >= 0) continue;
    var key = name.toLowerCase();
    if (!people[key]) { people[key] = {name: name, position: lastPos, shifts: 0, hours: 0, ANNUAL: 0, SICK: 0, UNPAID: 0, DOCTOR: 0, OFF: 0, unknown: []}; order.push(key); }
    var p = people[key];
    bm.days.forEach(function (day) {
      var col = hdr.cols[day];
      if (col === undefined) return;
      var raw = String(disp[r][col] || '').trim();
      if (!raw) return;
      var h = shiftHours_(raw, vals[r][col]);
      if (h !== null) { p.shifts++; p.hours += Math.max(0, h - c.breakHours); return; }
      for (var i = 0; i < MARKS.length; i++) if (MARKS[i].re.test(raw)) { p[MARKS[i].code]++; return; }
      p.unknown.push(bm.y + '-' + pad_(bm.m + 1) + '-' + pad_(day) + ' "' + raw + '"');
    });
  }
}

/** Finds the row whose cells contain day numbers 1..N (numbers, "1", or Date cells). */
function findDayHeader_(vals, c) {
  var rows = c.dayHeaderRow ? [c.dayHeaderRow - 1] : range_(0, Math.min(c.scanRows, vals.length));
  for (var i = 0; i < rows.length; i++) {
    var r = rows[i], cols = {}, n = 0;
    for (var j = (c.firstDayCol !== null ? c.firstDayCol : 0); j < vals[r].length; j++) {
      var v = vals[r][j], day = null;
      if (v instanceof Date) day = Number(fmt_(v, 'd'));
      else if (/^\d{1,2}$/.test(String(v).trim())) day = Number(v);
      if (day && day >= 1 && day <= 31 && cols[day] === undefined) { cols[day] = j; n++; }
    }
    if (n >= 28 && cols[1] !== undefined) return {row: r, cols: cols};
  }
  return null;
}

/** "8:00-17:00", "8.00 – 17.00", "8-17", "23:00-8:00" (overnight) or a plain number of hours. */
function shiftHours_(raw, val) {
  if (typeof val === 'number' && val > 0 && val <= 24) return val;
  var m = raw.replace(/\s+/g, '').match(/^(\d{1,2})(?:[:.](\d{2}))?(?:น\.)?[-–—~to]+(\d{1,2})(?:[:.](\d{2}))?(?:น\.)?$/i);
  if (!m) return null;
  var a = Number(m[1]) + Number(m[2] || 0) / 60, b = Number(m[3]) + Number(m[4] || 0) / 60;
  if (a > 24 || b > 24) return null;
  var h = b - a; if (h <= 0) h += 24;
  return h;
}

// ---------- helpers ----------
function colIdx_(letters) { var s = String(letters).toUpperCase().trim(), n = 0; for (var i = 0; i < s.length; i++) n = n * 26 + (s.charCodeAt(i) - 64); return n - 1; }
function fmt_(d, f) { return Utilities.formatDate(d, TZ, f); }
function isoDate_(s) { var p = s.split('-'); return new Date(Number(p[0]), Number(p[1]) - 1, Number(p[2])); }
function pad_(n) { return (n < 10 ? '0' : '') + n; }
function round2_(x) { return Math.round(x * 100) / 100; }
function range_(a, b) { var r = []; for (var i = a; i < b; i++) r.push(i); return r; }
function esc_(s) { return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;'); }
function csvCell_(v) { v = String(v); return /[",\n]/.test(v) ? '"' + v.replace(/"/g, '""') + '"' : v; }

return {dryRun: dryRun, createTimesheetDraft: createTimesheetDraft};
})(T_props_('ST5'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 60-Coverage.gs =====
/** GENERATED by build-test-project.sh from schedule-coverage.gs — do not edit here. Module SC (TEST sandbox). */
var SC = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — М-3.1 Staff schedule coverage check (Schedule 26). DRAFT TEMPLATE, NOT DEPLOYED.
 *
 * Reads the Schedule-26 month tabs (same layout as stage5-timesheet.gs:
 * Position | Name | 1..31 | Total Hrs.) for the next WINDOW_DAYS and reports:
 *   - hours between OPEN_HOUR and CLOSE_HOUR with NO admin on shift (gaps)
 *   - hours with only one admin (info, e.g. reception cannot be left)
 *   - leave marks (Annual / Sick / Leave without money) and days with >= 2 admins on leave
 *   - next month tab missing (e.g. Nov not created by the 20th)
 *   - unreadable cells
 * Read-only on the sheet. Output: log (dryRun) or a Gmail DRAFT to info@ (draft mode). Never sends.
 * Intended use: Monday digest inside the existing 10:07 run (Lead reads the draft/log);
 * no new Lead runs. Owner of the schedule from 01.10: per George 29.09 "Lena + Place Ops"
 * — the Lena part is only a proposal, not agreed.
 *
 * Script Properties (all optional):
 *   SCHEDULE_SHEET_ID  default Schedule 26 id
 *   TAB_NAMES          JSON 12 names, default Jan..Dec
 *   POSITION_COL=A NAME_COL=B  HEADER_SCAN_ROWS=10
 *   ADMIN_RE           regex for admin rows, default 'admin'
 *   EXCLUDE_NAMES      comma list (e.g. 'Aiz' after 30.09)
 *   OPEN_HOUR=8 CLOSE_HOUR=23 WINDOW_DAYS=14
 *   REPORT_SINGLE      'true' = also list hours with only one admin (default off, noisy)
 *   COVERAGE_MODE      'dry' | 'draft'   DIGEST_TO default info@placecoworking.com
 */

var SC_TZ = 'Asia/Bangkok';
var SC_DEFAULT_ID = '1eQTyAIjlnGlyYy_5FDfDOAbT5NXaAeYAR_QPnWWBrZc';
var SC_TABS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
var SC_LEAVE_RE = /(annual|sick|leave|unpaid|doctor|ลา|ป่วย|พักร้อน)/i;
var SC_OFF_RE = /^(off|day\s*off|หยุด|-|x)$/i;

function dryRunCoverage() { return coverage_('dry'); }
function runCoverage() { var m = PropertiesService.getScriptProperties().getProperty('COVERAGE_MODE') || 'dry'; return coverage_(m === 'draft' ? 'draft' : 'dry'); }

function scCfg_() {
  var p = PropertiesService.getScriptProperties();
  var g = function (k, d) { var v = p.getProperty(k); return (v === null || v === '') ? d : v; };
  return {
    id: g('SCHEDULE_SHEET_ID', SC_DEFAULT_ID), tabs: JSON.parse(g('TAB_NAMES', JSON.stringify(SC_TABS))),
    posCol: scCol_(g('POSITION_COL', 'A')), nameCol: scCol_(g('NAME_COL', 'B')), scan: Number(g('HEADER_SCAN_ROWS', '10')),
    adminRe: new RegExp(g('ADMIN_RE', 'admin'), 'i'),
    exclude: g('EXCLUDE_NAMES', '').split(',').map(function (s) { return s.trim().toLowerCase(); }).filter(String),
    open: Number(g('OPEN_HOUR', '8')), close: Number(g('CLOSE_HOUR', '23')), win: Number(g('WINDOW_DAYS', '14')),
    to: g('DIGEST_TO', 'info@placecoworking.com'), single: g('REPORT_SINGLE', 'false') === 'true'
  };
}

function coverage_(mode) {
  var c = scCfg_(), ss = SpreadsheetApp.openById(c.id);
  var s = Utilities.formatDate(new Date(), SC_TZ, 'yyyy-MM-dd').split('-');
  var start = new Date(+s[0], +s[1] - 1, +s[2]);
  var cache = {}, lines = [], warn = [], gapsTotal = 0;
  for (var i = 0; i < c.win; i++) {
    var d = new Date(start.getFullYear(), start.getMonth(), start.getDate() + i);
    var tab = c.tabs[d.getMonth()];
    if (!(tab in cache)) cache[tab] = scReadTab_(ss.getSheetByName(tab), c);
    var mdata = cache[tab];
    if (!mdata) { if (warn.indexOf('Нет вкладки ' + tab) < 0) warn.push('Нет вкладки ' + tab + ' (график на ' + tab + ' не составлен)'); continue; }
    var slots = [], leave = [], unknown = [];
    for (var h = c.open; h < c.close; h++) slots.push([]);
    mdata.people.forEach(function (p) {
      var raw = p.days[d.getDate()] || '';
      if (!raw) return;
      var sh = scShift_(raw);
      if (sh) { for (var h = c.open; h < c.close; h++) if (scCovers_(sh, h)) slots[h - c.open].push(p.name); return; }
      if (SC_LEAVE_RE.test(raw)) { leave.push(p.name + ' (' + raw + ')'); return; }
      if (SC_OFF_RE.test(raw)) return;
      unknown.push(p.name + ' "' + raw + '"');
    });
    var gaps = [], single = [];
    slots.forEach(function (arr, k) { var h = c.open + k; if (!arr.length) gaps.push(h); else if (arr.length === 1) single.push(h); });
    gapsTotal += gaps.length;
    var label = Utilities.formatDate(d, SC_TZ, 'EEE dd.MM');
    var parts = [];
    if (gaps.length) parts.push('🔴 НЕТ админа: ' + scRanges_(gaps));
    if (single.length && c.single) parts.push('🟡 один админ: ' + scRanges_(single));
    if (leave.length) parts.push((leave.length >= 2 ? '⚠️ ' : '') + 'отпуск/больничный: ' + leave.join(', '));
    if (unknown.length) parts.push('❓ ' + unknown.join('; '));
    if (parts.length) lines.push(label + ': ' + parts.join(' · '));
  }
  // next month tab must exist by the 20th
  if (start.getDate() >= 20) { var nt = c.tabs[(start.getMonth() + 1) % 12]; if (!ss.getSheetByName(nt)) warn.push('К 20-му нет вкладки следующего месяца: ' + nt); }
  var subject = 'Покрытие смен ' + Utilities.formatDate(start, SC_TZ, 'dd.MM') + ' + ' + c.win + ' дн.: дыр ' + gapsTotal + ' ч';
  var body = (lines.length ? lines.join('\n') : 'Дыр и отпусков нет.') + (warn.length ? '\n\n' + warn.join('\n') : '') +
    '\n\nЧасы ' + c.open + ':00–' + c.close + ':00, только строки Admin. Черновик, никому не отправлено.';
  if (mode === 'draft') GmailApp.createDraft(c.to, subject, body);
  Logger.log('[coverage ' + mode + '] ' + subject + '\n' + body);
  return {subject: subject, body: body, gaps: gapsTotal};
}

function scReadTab_(sh, c) {
  if (!sh) return null;
  var vals = sh.getDataRange().getValues(), disp = sh.getDataRange().getDisplayValues();
  var hdr = null;
  for (var r = 0; r < Math.min(c.scan, vals.length) && !hdr; r++) {
    var cols = {}, n = 0;
    for (var j = 0; j < vals[r].length; j++) {
      var v = vals[r][j], day = v instanceof Date ? v.getDate() : (/^\d{1,2}$/.test(String(v).trim()) ? Number(v) : null);
      if (day && day <= 31 && cols[day] === undefined) { cols[day] = j; n++; }
    }
    if (n >= 28 && cols[1] !== undefined) hdr = {row: r, cols: cols};
  }
  if (!hdr) return {people: []};
  var people = [], lastPos = '';
  for (var r2 = hdr.row + 1; r2 < disp.length; r2++) {
    var pos = String(disp[r2][c.posCol] || '').trim(), name = String(disp[r2][c.nameCol] || '').trim();
    if (pos) lastPos = pos;
    if (!name || !c.adminRe.test(lastPos) || c.exclude.indexOf(name.toLowerCase()) >= 0) continue;
    var days = {};
    Object.keys(hdr.cols).forEach(function (dd) { days[dd] = String(disp[r2][hdr.cols[dd]] || '').trim(); });
    people.push({name: name, pos: lastPos, days: days});
  }
  return {people: people};
}

/** "8:00-17:00", "14.00 – 23.00", "8-17", "23:00-8:00" -> {a, b} in hours (b may be > 24). */
function scShift_(raw) {
  var m = raw.replace(/\s+/g, '').match(/^(\d{1,2})(?:[:.](\d{2}))?[-–—~]+(\d{1,2})(?:[:.](\d{2}))?$/);
  if (!m) return null;
  var a = +m[1] + (+m[2] || 0) / 60, b = +m[3] + (+m[4] || 0) / 60;
  if (a > 24 || b > 24) return null;
  if (b <= a) b += 24;
  return {a: a, b: b};
}
function scCovers_(sh, h) { return (sh.a <= h && sh.b >= h + 1) || (sh.a <= h + 24 && sh.b >= h + 25); }
function scRanges_(hours) {
  var out = [], s = hours[0], p = hours[0];
  for (var i = 1; i <= hours.length; i++) {
    if (hours[i] === p + 1) { p = hours[i]; continue; }
    out.push(s + ':00–' + (p + 1) + ':00'); s = p = hours[i];
  }
  return out.join(', ');
}
function scCol_(l) { var s = String(l).toUpperCase(), n = 0; for (var i = 0; i < s.length; i++) n = n * 26 + s.charCodeAt(i) - 64; return n - 1; }

return {coverage_: coverage_, scCfg_: scCfg_, scReadTab_: scReadTab_, scShift_: scShift_};
})(T_props_('SC'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 70-Leave.gs =====
/** GENERATED by build-test-project.sh from leave-requests.gs — do not edit here. Module LV (TEST sandbox). */
var LV = (function (PropertiesService, SpreadsheetApp, GmailApp, MailApp, UrlFetchApp, ScriptApp, Logger) {

/**
 * Place Coworking — G-13 Staff leave requests through the bot. DRAFT, NOT LIVE (scheme per George 30.09.2026 10:40;
 * staged in the TEST project only, writes only Schedule 26 TEST).
 *
 * Flow:
 *   1. Employee writes to @PlaceLeadBot: «/leave <vacation|dayoff> dd.mm[-dd.mm] [reason]»
 *      (also: отпуск / выходной / พักร้อน / หยุด; optional sick / unpaid / doctor).
 *   2. leaveRequest_() adds a row to tab «Leave» and returns ONE approval card per approver: BOTH Lena and George
 *      (Script Property LEAVE_APPROVERS, default "George,Lena").
 *   3. Either approver answers «/approve L…» or «/reject L… reason». The first decision wins; a later one gets
 *      «already approved/rejected by …». Anyone not in LEAVE_APPROVERS is refused.
 *   4. leaveDecide_() updates the row, returns the message for the employee and a note for the other approver,
 *      and on approve marks the days in Schedule 26: vacation -> «Annual leave», day off -> «off» (sick -> «Sick leave»,
 *      unpaid -> «Leave with out money», doctor -> «Doctor»; the words stage5-timesheet understands).
 *      Only empty / «off» cells are filled; a cell with a shift is NOT overwritten, it is reported as a conflict.
 * Pure functions: sending is done by the caller (bridge hook later; TEST: relay to George's DM).
 *
 * Script Properties: LEAVE_SHEET_ID (spreadsheet with tab «Leave»), SCHEDULE_SHEET_ID, LEAVE_APPROVERS.
 */
var LV_TZ = 'Asia/Bangkok';
var LV_TABS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
var LV_HEAD = ['id', 'requested_at', 'employee', 'tg_user', 'tg_chat_id', 'type', 'from', 'to', 'days', 'reason', 'status', 'decided_by', 'decided_at', 'schedule_written', 'conflicts', 'sent_to'];
var LV_MARK = {vacation: 'Annual leave', dayoff: 'off', sick: 'Sick leave', unpaid: 'Leave with out money', doctor: 'Doctor'};
var LV_LABEL = {vacation: 'Отпуск / Vacation', dayoff: 'Выходной / Day off', sick: 'Больничный / Sick', unpaid: 'За свой счёт / Unpaid', doctor: 'Врач / Doctor'};
var LV_ALIAS = {vacation: 'vacation', annual: 'vacation', 'отпуск': 'vacation', 'พักร้อน': 'vacation', dayoff: 'dayoff', off: 'dayoff',
  'выходной': 'dayoff', 'หยุด': 'dayoff', sick: 'sick', unpaid: 'unpaid', doctor: 'doctor'};
var LV_OFF_RE = /^(off|day\s*off|หยุด|-|x)?$/i;

function lvProps_() { return PropertiesService.getScriptProperties(); }
function lvApprovers_() { return String(lvProps_().getProperty('LEAVE_APPROVERS') || 'George,Lena').split(',').map(function (x) { return x.trim(); }).filter(String); }
function lvSheet_() {
  var ss = SpreadsheetApp.openById(lvProps_().getProperty('LEAVE_SHEET_ID')), sh = ss.getSheetByName('Leave');
  if (!sh) { sh = ss.insertSheet('Leave'); sh.appendRow(LV_HEAD); }
  return sh;
}

/** «/leave vacation 05.10-07.10 family» -> {type, from, to, days, comment} or {error}. */
function leaveParse_(text, now) {
  var m = String(text).trim().match(/^\/leave\s+(\S+)\s+(\d{1,2})\.(\d{1,2})(?:\.(\d{4}))?(?:\s*[-–]\s*(\d{1,2})\.(\d{1,2})(?:\.(\d{4}))?)?\s*(.*)$/i);
  var type = m && LV_ALIAS[m[1].toLowerCase()];
  if (!m || !type) return {error: 'Format: /leave vacation|dayoff dd.mm[-dd.mm] [reason]  (отпуск / выходной)'};
  var y = Number(Utilities.formatDate(now || new Date(), LV_TZ, 'yyyy'));
  var from = new Date(Number(m[4] || y), Number(m[3]) - 1, Number(m[2]));
  var to = m[5] ? new Date(Number(m[7] || m[4] || y), Number(m[6]) - 1, Number(m[5])) : from;
  if (to < from) return {error: 'End date is before start date'};
  var days = Math.round((to - from) / 86400000) + 1;
  if (days > 31) return {error: 'Max 31 days per request'};
  return {type: type, from: from, to: to, days: days, comment: m[8] || ''};
}

/** Registers the request. Returns {id, cards: [{to, text}] for EVERY approver, reply, error}. */
function leaveRequest_(emp, text, now) {
  now = now || new Date();
  var r = leaveParse_(text, now);
  if (r.error) return {error: r.error, reply: '❗ ' + r.error};
  var id = 'L' + Utilities.formatDate(now, LV_TZ, 'yyMMddHHmmss');
  var d = function (x) { return Utilities.formatDate(x, LV_TZ, 'dd.MM.yyyy'); };
  lvSheet_().appendRow([id, Utilities.formatDate(now, LV_TZ, 'yyyy-MM-dd HH:mm'), emp.name, emp.user || '', String(emp.chatId || ''),
    r.type, d(r.from), d(r.to), r.days, r.comment, 'pending', '', '', '', '', lvApprovers_().join(', ')]);
  var text = '🗓 Запрос ' + id + '\n' + emp.name + ': ' + LV_LABEL[r.type] + ', ' + d(r.from) + (r.days > 1 ? '–' + d(r.to) : '') +
    ' (' + r.days + ' дн.)' + (r.comment ? '\nПричина: ' + r.comment : '') +
    '\n\nРешает любой из: ' + lvApprovers_().join(' / ') + '.\nОтвет: /approve ' + id + '  или  /reject ' + id + ' причина';
  return {id: id, cards: lvApprovers_().map(function (a) { return {to: a, text: text}; }),
    reply: '✅ Запрос ' + id + ' отправлен ' + lvApprovers_().join(' и ') + '.'};
}

/** decision 'approve' | 'reject' by one of LEAVE_APPROVERS. First decision wins.
 *  Returns {status, employeeMsg, otherMsg: {to, text}, written, conflicts}. */
function leaveDecide_(id, decision, by, reason, now) {
  now = now || new Date();
  var who = lvApprovers_().filter(function (a) { return a.toLowerCase() === String(by).trim().toLowerCase(); })[0];
  if (!who) return {status: 'not allowed', reply: '⛔ Решать могут только: ' + lvApprovers_().join(', ')};
  var sh = lvSheet_(), v = sh.getDataRange().getValues();
  for (var r = 1; r < v.length; r++) {
    if (String(v[r][0]) !== id) continue;
    if (v[r][10] !== 'pending') return {status: 'already ' + v[r][10] + ' by ' + v[r][11], reply: 'ℹ️ ' + id + ' уже ' + v[r][10] + ' (' + v[r][11] + ')'};
    var row = v[r], res = {written: 0, conflicts: []};
    row[10] = decision === 'approve' ? 'approved' : 'rejected'; row[11] = who; row[12] = Utilities.formatDate(now, LV_TZ, 'yyyy-MM-dd HH:mm');
    if (decision === 'approve') { res = leaveWriteSchedule_(row[2], row[5], lvDate_(row[6]), lvDate_(row[7])); row[13] = res.written; row[14] = res.conflicts.join('; '); }
    sh.getRange(r + 1, 1, 1, LV_HEAD.length).setValues([row]);
    var msg = decision === 'approve'
      ? '✅ ' + LV_LABEL[row[5]] + ' ' + id + ' одобрен (' + row[6] + '–' + row[7] + ', ' + who + '). В графике отмечено дней: ' + res.written + (res.conflicts.length ? '. Лена/Place Ops проверят смены: ' + res.conflicts.join(', ') : '')
      : '❌ ' + LV_LABEL[row[5]] + ' ' + id + ' отклонён (' + who + ')' + (reason ? ': ' + reason : '');
    var others = lvApprovers_().filter(function (a) { return a !== who; });
    return {status: row[10], employeeMsg: msg, written: res.written, conflicts: res.conflicts,
      otherMsg: others.map(function (a) { return {to: a, text: 'ℹ️ ' + id + ' (' + row[2] + '): ' + row[10] + ' — решил(а) ' + who + '. Решать больше не нужно.'}; })};
  }
  return {status: 'not found'};
}

function leaveWriteSchedule_(name, type, from, to) {
  var ss = SpreadsheetApp.openById(lvProps_().getProperty('SCHEDULE_SHEET_ID')), mark = LV_MARK[type], written = 0, conflicts = [], cache = {};
  for (var d = new Date(from); d <= to; d = new Date(d.getFullYear(), d.getMonth(), d.getDate() + 1)) {
    var tab = LV_TABS[d.getMonth()], t = cache[tab] || (cache[tab] = lvTab_(ss.getSheetByName(tab), name));
    var label = Utilities.formatDate(d, LV_TZ, 'dd.MM');
    if (!t.sh) { conflicts.push(label + ' нет вкладки ' + tab); continue; }
    if (t.row < 0) { conflicts.push(label + ' нет строки «' + name + '»'); continue; }
    var col = t.cols[d.getDate()];
    if (col === undefined) { conflicts.push(label + ' нет колонки дня'); continue; }
    var cur = String(t.disp[t.row][col] || '').trim();
    if (!LV_OFF_RE.test(cur) && cur !== mark) { conflicts.push(label + ' стоит «' + cur + '»'); continue; }
    t.sh.getRange(t.row + 1, col + 1).setValue(mark); written++;
  }
  return {written: written, conflicts: conflicts};
}
function lvTab_(sh, name) {
  if (!sh) return {sh: null};
  var vals = sh.getDataRange().getValues(), disp = sh.getDataRange().getDisplayValues(), cols = {}, hr = -1;
  for (var r = 0; r < Math.min(10, vals.length) && hr < 0; r++) {
    var c = {}, n = 0;
    for (var j = 0; j < vals[r].length; j++) { var x = vals[r][j]; if (x instanceof Date || Object.prototype.toString.call(x) === '[object Date]') { if (c[x.getDate()] === undefined) { c[x.getDate()] = j; n++; } } }
    if (n >= 28) { hr = r; cols = c; }
  }
  var row = -1;
  for (var r2 = hr + 1; r2 < disp.length && hr >= 0; r2++) if (String(disp[r2][1]).trim().toLowerCase() === String(name).trim().toLowerCase()) { row = r2; break; }
  return {sh: sh, cols: cols, row: row, disp: disp};
}
function lvDate_(s) { var p = String(s).split('.'); return new Date(Number(p[2]), Number(p[1]) - 1, Number(p[0])); }

return {leaveParse_: leaveParse_, leaveRequest_: leaveRequest_, leaveDecide_: leaveDecide_};
})(T_props_('LV'), T_SS, T_GMAIL, T_MAIL, T_FETCH, T_SCRIPT, T_LOGGER);

// ===== 90-Tests.gs =====
/** PLACE automations TEST — test entry points. Run from the editor (Run ▸ function). No triggers. */
var T_FAKE_CHAT = {id: -1009990001, title: 'Тех вопросы TEST', type: 'supergroup'};

function test_all() {
  return [test_guard(), test_stage6(), test_issues(), test_issuesBridgeHook(), test_bookings(), test_keyholders(), test_timesheet(), test_leave()]
    .map(function (r) { return r.status; });
}

/** Self-test of the safety layer: every call must be BLOCKED. */
function test_guard() {
  return T_fixture_('guard', 'test_guard', function () {
    var out = [];
    [function () { T_SS.openById(P_IDS.inbox).getSheetByName('queue').appendRow(['x']); },   // prod write
     function () { T_SS.openById(P_IDS.resident).getSheets()[0].getRange(1, 1).setValue('x'); }, // prod write
     function () { T_SS.openById('1AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'); },              // unknown sheet
     function () { T_FETCH.fetch('https://example.com/'); },                                       // non-Telegram fetch
     function () { T_SCRIPT.newTrigger('x'); }]                                                    // triggers from modules
      .forEach(function (f, i) { try { f(); out.push(i + ':NOT BLOCKED'); } catch (e) { out.push(i + ':blocked'); } });
    var ro = T_SS.openById(P_IDS.inbox).getSheetByName('queue').getLastRow();                      // prod read works
    if (out.join(',').indexOf('NOT') >= 0) throw new Error('GUARD FAIL ' + out.join(','));
    return 'all 5 blocked: ' + out.join(',') + '; prod read OK (queue rows ' + ro + ')';
  });
}

/** Stage 6: offices + electricity task for Lena (writes Issues in Place Inbox TEST). */
function test_stage6() { return T_fixture_('stage6', 'ST6.run_(draft→stub)', function () { return ST6.run_('draft'); }); }
function test_stage6Reset() { return T_fixture_('stage6', 'ST6.resetSentLog', function () { ST6.resetSentLog(); return 'SENT_LOG cleared'; }); }

/** Issues: new issue, second issue, reply in progress, reply «готово» closes, digests. */
function test_issues() {
  return T_fixture_('issues', 'ISS.issuesHandle_ + digest', function () {
    var sh = ISS.issuesSheet_(), t = Math.floor(Date.now() / 1000), base = 900000 + (t % 90000), r = [];
    r.push(ISS.issuesHandle_(sh, {chat: T_FAKE_CHAT, message_id: base, date: t, from: {username: 'som_test'}}, 'TEST: кондиционер на 3 этаже течёт', 'Som (TEST)'));
    r.push(ISS.issuesHandle_(sh, {chat: T_FAKE_CHAT, message_id: base + 1, date: t + 60, from: {username: 'tangmo_test'}}, 'TEST: ชั้น 1 ไฟดับ 2 ดวง', 'Tangmo (TEST)'));
    r.push(ISS.issuesHandle_(sh, {chat: T_FAKE_CHAT, message_id: base + 2, date: t + 120, from: {username: 'som_test'}, reply_to_message: {message_id: base}}, 'смотрю, нужна деталь', 'Som (TEST)'));
    r.push(ISS.issuesHandle_(sh, {chat: T_FAKE_CHAT, message_id: base + 3, date: t + 180, from: {username: 'som_test'}, reply_to_message: {message_id: base + 1}}, 'готово', 'Som (TEST)'));
    r.push(ISS.issuesHandle_(sh, {chat: T_FAKE_CHAT, message_id: base + 4, date: t + 240, from: {username: 'placeleadbot'}}, 'bot echo', 'bot'));
    return {handled: r, morning: ISS.issuesDigest_('morning'), evening: ISS.issuesDigest_('evening')};
  });
}

/** Bridge hook as it would sit in poll(): only «Тех вопросы» and not edited messages go to Issues. */
function test_issuesBridgeHook() {
  return T_fixture_('issues', 'bridge hook simulation', function () {
    var t = Math.floor(Date.now() / 1000), base = 990000 + (t % 9000), out = [];
    var updates = [
      {message: {chat: T_FAKE_CHAT, message_id: base, date: t, from: {username: 'kate_test'}, text: 'TEST: ชั้น 4 น้ำรั่ว'}},
      {message: {chat: {id: -1009990002, title: 'PLACE Team TEST'}, message_id: base + 1, date: t, from: {username: 'kate_test'}, text: 'TEST: not an issue chat'}},
      {edited_message: {chat: T_FAKE_CHAT, message_id: base, date: t, from: {username: 'kate_test'}, text: 'edited'}}
    ];
    updates.forEach(function (u) {
      var m = u.message || u.edited_message, chat = (m.chat && m.chat.title) || '', text = m.text, name = (m.from && m.from.username) || '?';
      if (ISS.ISSUES_CHAT_RE.test(chat) && !(u.edited_message)) out.push(chat + ' -> ' + ISS.issuesHandle_(ISS.issuesSheet_(), m, text, name));
      else out.push(chat + ' -> skipped');
    });
    return out;
  });
}

/** G-5: bookings for 01.10.2026 (TEST booking in Meeting room) and for today. */
function test_bookings() {
  return T_fixture_('bookings', 'BKG.bookingsToday_', function () {
    return BKG.bookingsToday_(new Date('2026-10-01T10:07:00+07:00')) + '\n\n' + BKG.bookingsToday_(new Date('2026-12-20T10:07:00+07:00'));
  });
}

/** C8: active 24/7 key holders (TEST rows 303-305 in Лист1). */
function test_keyholders() { return T_fixture_('keyholders', 'KH.keyholders247_', function () { return KH.keyholders247_(new Date('2026-09-30T22:30:00+07:00')); }); }

/** Stage 5: timesheet dry run + "draft" (stub). Calendar month, counted to the 28th; 29..end = after cutoff; prev month 29..end = adjustments. */
function test_timesheet() {
  return T_fixture_('timesheet', 'ST5.dryRun + createTimesheetDraft(stub)', function () {
    var r = ST5.dryRun();
    return {subject: r.subject, period: r.fromIso + '..' + r.toIso, countedTo: r.cutIso, warnings: r.warnings, people: r.rows.length,
      afterCutoff: r.afterCutoff, prevAdjustments: r.prevAdjustments, draft: ST5.createTimesheetDraft()};
  });
}

/** G-13 leave via bot (staged, scheme 30.09 10:40): request -> cards to BOTH George and Lena -> either decides ->
 *  employee notified + Schedule 26 TEST marked; second decision refused; non-approver refused; bad format. */
function test_leave() {
  return T_fixture_('leave', 'LV.leaveRequest_ + leaveDecide_ (George + Lena)', function () {
    var now = new Date();
    var bad = LV.leaveRequest_({name: 'Tangmo', user: 'tangmo_test', chatId: 1}, '/leave holiday tomorrow', now);
    var a = LV.leaveRequest_({name: 'Tangmo', user: 'tangmo_test', chatId: 1}, '/leave vacation 11.10-12.10 TEST family', now);
    a.cards.forEach(function (c) { T_relay_(c.to, 'TG DM ' + c.to + ' (approval card)', c.text); });
    var nope = LV.leaveDecide_(a.id, 'approve', 'Kate', '', now);
    var ok = LV.leaveDecide_(a.id, 'approve', 'Lena', '', now);
    var late = LV.leaveDecide_(a.id, 'reject', 'George', '', now);
    T_relay_('Tangmo', 'TG DM Tangmo', ok.employeeMsg);
    ok.otherMsg.forEach(function (m) { T_relay_(m.to, 'TG DM ' + m.to, m.text); });
    var b = LV.leaveRequest_({name: 'Kate', user: 'kate_test', chatId: 2}, '/leave выходной 14.10 TEST', new Date(now.getTime() + 1000));
    var no = LV.leaveDecide_(b.id, 'reject', 'George', 'TEST reason', now);
    T_relay_('Kate', 'TG DM Kate', no.employeeMsg);
    return {badFormat: bad.error, request: a.id, cardsTo: a.cards.map(function (c) { return c.to; }), nonApprover: nope.status,
      approveByLena: {status: ok.status, written: ok.written, conflicts: ok.conflicts}, secondDecision: late.status, dayoffRejectByGeorge: no.status};
  });
}

// ===== 95-Scheduled.gs =====
/**
 * PLACE automations TEST — scheduled TEST mode (George OK 30.09.2026 10:02).
 * Production sheets READ-ONLY, writes only to Place Inbox TEST (Issues, Log), every outgoing message relayed to
 * George's DM with @PlaceLeadBot (see T_relay_). Triggers: installTestTriggers() / removeTestTriggers().
 *
 * One-time setup (see TEST-PLAN.md §2b):
 *   1. Project Settings ▸ Script properties ▸ add TG_TOKEN = <token of @PlaceLeadBot>  (never in code, never in Log).
 *      Optional: GEORGE_CHAT_ID (if known), GEORGE_TG_USERNAME (e.g. without @), CASH_ANCHOR_DATE (yyyy-mm-dd).
 *   2. Run setupTestProperties()  -> checks the token (getMe), finds/sets GEORGE_CHAT_ID, writes a summary to Log.
 *   3. Run sendTestPing()          -> George gets «🧪 TEST ping».
 *   4. Run installTestTriggers()   -> 7 time triggers (Asia/Bangkok).
 */
var T_JOBS = [
  // handler,            kind,     when (Asia/Bangkok; Apps Script runs within ~±15 min of nearMinute)
  ['job_stage6',         'daily',  9, 5,  'stage6 office reminders + electricity tasks'],
  ['job_coverage',       'daily',  9, 10, 'schedule-coverage'],
  ['job_bookings',       'daily',  10, 7, 'bookings-today (10:07 summary)'],
  ['job_issuesMorning',  'daily',  10, 7, 'issues summary morning'],
  ['job_issuesEvening',  'daily',  23, 10, 'issues summary evening'],
  ['job_timesheet',      'month28', 9, 30, 'timesheet draft for the accountant (28th; period = current month, 29..end = next month adjustments)'],
  ['job_cashReminder',   'every3', 20, 0, 'cash-deposit reminder for the evening admin (every 3 days)']
];

// ---------- setup ----------
function setupTestProperties() {
  return T_run_('setup', 'setupTestProperties', function () {
    var p = PropertiesService.getScriptProperties(), out = [];
    var tok = p.getProperty('TG_TOKEN');
    if (!tok) out.push('TG_TOKEN: NOT SET. Add it by hand: Project Settings ▸ Script properties ▸ TG_TOKEN. Relay stays LOG ONLY.');
    else {
      var r = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/getMe', {muteHttpExceptions: true});
      var ok = r.getResponseCode() === 200 && JSON.parse(r.getContentText()).ok;
      out.push('TG_TOKEN: set, getMe ' + (ok ? 'OK @' + JSON.parse(r.getContentText()).result.username : 'FAILED HTTP ' + r.getResponseCode()));
    }
    var chat = p.getProperty('GEORGE_CHAT_ID');
    if (!chat) {
      var c = T_findGeorgeChatId_();
      out.push('GEORGE_CHAT_ID lookup in production queue (read-only): ' + c.note);
      if (c.id) { p.setProperty('GEORGE_CHAT_ID', c.id); chat = c.id; }
    }
    out.push('GEORGE_CHAT_ID: ' + (chat ? chat : 'NOT SET → relay LOG ONLY. George: press /start in @PlaceLeadBot, then run setupTestProperties() again, or set GEORGE_CHAT_ID by hand.'));
    if (!p.getProperty('CASH_ANCHOR_DATE')) { p.setProperty('CASH_ANCHOR_DATE', Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd')); }
    out.push('CASH_ANCHOR_DATE: ' + p.getProperty('CASH_ANCHOR_DATE'));
    out.push('Triggers now: ' + ScriptApp.getProjectTriggers().map(function (t) { return t.getHandlerFunction(); }).join(', '));
    return out.join('\n');
  });
}

/** George's private chat id: rows «личка боту» in the production queue (bridge log), matched by GEORGE_TG_USERNAME or name. */
function T_findGeorgeChatId_() {
  var p = PropertiesService.getScriptProperties(), user = String(p.getProperty('GEORGE_TG_USERNAME') || '').replace(/^@/, '').toLowerCase();
  var sh = T_SS.openById(P_IDS.inbox).getSheetByName('queue');
  if (!sh) return {id: null, note: 'queue tab not found'};
  var v = sh.getDataRange().getDisplayValues(), found = {};
  for (var r = 1; r < v.length; r++) {
    var chat = v[r][1], id = String(v[r][2] || ''), name = v[r][3], un = String(v[r][4] || '').replace(/^@/, '').toLowerCase();
    if (!/личка боту/i.test(chat) || !/^\d+$/.test(id)) continue;
    if ((user && un === user) || (!user && /george|geo\b|джордж/i.test(name))) found[id] = name + (un ? ' @' + un : '');
  }
  var ids = Object.keys(found);
  if (ids.length === 1) return {id: ids[0], note: 'found ' + ids[0] + ' (' + found[ids[0]] + ')'};
  return {id: null, note: ids.length ? 'ambiguous: ' + JSON.stringify(found) + ' → set GEORGE_TG_USERNAME' : 'no private chat from George yet'};
}

function sendTestPing() {
  var prev = T_CTX; T_CTX = {relay: true, mail: null};
  try {
    return T_run_('ping', 'sendTestPing', function () {
      var p = PropertiesService.getScriptProperties(), tok = p.getProperty('TG_TOKEN'), chat = p.getProperty('GEORGE_CHAT_ID');
      if (!tok || !chat || !/^\d{5,15}$/.test(chat)) throw new Error('TG_TOKEN or GEORGE_CHAT_ID missing → run setupTestProperties()');
      var r = UrlFetchApp.fetch('https://api.telegram.org/bot' + tok + '/sendMessage', {method: 'post', contentType: 'application/json',
        payload: JSON.stringify({chat_id: chat, text: '🧪 TEST ping from «PLACE automations TEST», ' + T_now_() + ' ICT'}), muteHttpExceptions: true});
      if (r.getResponseCode() !== 200) throw new Error('sendMessage HTTP ' + r.getResponseCode());
      return 'ping sent to GEORGE_CHAT_ID';
    });
  } finally { T_CTX = prev; }
}

// ---------- triggers ----------
function installTestTriggers() {
  removeTestTriggers();
  var made = T_JOBS.map(function (j) {
    var b = ScriptApp.newTrigger(j[0]).timeBased().inTimezone('Asia/Bangkok');
    if (j[1] === 'daily') b = b.everyDays(1).atHour(j[2]).nearMinute(j[3]);
    else if (j[1] === 'every3') b = b.everyDays(3).atHour(j[2]).nearMinute(j[3]);
    else if (j[1] === 'month28') b = b.onMonthDay(28).atHour(j[2]).nearMinute(j[3]);
    b.create();
    return j[0] + ' ' + j[1] + ' ' + j[2] + ':' + ('0' + j[3]).slice(-2);
  });
  T_log_('triggers', 'installTestTriggers', 'OK', made.join('\n'));
  return made;
}
function removeTestTriggers() {
  var names = T_JOBS.map(function (j) { return j[0]; }), n = 0;
  ScriptApp.getProjectTriggers().forEach(function (t) { if (names.indexOf(t.getHandlerFunction()) >= 0) { ScriptApp.deleteTrigger(t); n++; } });
  T_log_('triggers', 'removeTestTriggers', 'OK', 'removed ' + n);
  return n;
}

// ---------- jobs (trigger handlers) ----------
function ST6_prop_(k) { return T_props_('ST6').getScriptProperties().getProperty(k); }
function job_stage6() {
  return T_job_('stage6', 'job_stage6 (prod Resident info read-only)', function (to) {
    if (to === 'info@placecoworking.com') return {recipient: 'Place Ops / George (offices digest)', channel: 'email draft (info@) to ' + to};
    return {recipient: 'tenant ' + to, channel: 'email to tenant ' + to + ' (Gmail draft on info@)'};
  }, function () {
    var reg = T_SS.openById(ST6_prop_('RESIDENT_SHEET_ID')).getSheetByName(ST6_prop_('TAB_NAME'));
    if (!reg || reg.getLastRow() < 2) return 'Office rent is empty in production Resident info: nothing to check (no relay)';
    var r = ST6.run_('draft');
    var rows = T_SS.openById(T_IDS.inbox).getSheetByName('Issues').getDataRange().getValues(), today = Utilities.formatDate(new Date(), 'Asia/Bangkok', 'yyyy-MM-dd');
    rows.filter(function (x) { return /^elec:/.test(x[0]) && String(x[1]).indexOf(today) === 0; }).forEach(function (x) {
      T_relay_('Lena', 'TG DM Lena', '⚡ ' + x[4] + '\n(задача в Issues: ' + x[0] + ')');
    });
    return r;
  });
}
function job_coverage() {
  return T_job_('coverage', 'job_coverage (prod Schedule 26 read-only)', function (to) {
    return {recipient: 'Lena + Place Ops (schedule coverage)', channel: 'email draft (info@) to ' + to};
  }, function () { var r = SC.coverage_('draft'); return {subject: r.subject, gaps: r.gaps}; });
}
function job_bookings() {
  return T_job_('bookings', 'job_bookings (prod Events and booking read-only)', null, function () {
    var t = BKG.bookingsToday_(new Date());
    T_relay_('PLACE Team', 'TG group PLACE Team (10:07 summary)', t);
    return t;
  });
}
function job_issuesMorning() { return T_issuesJob_('morning', 'TG group PLACE Team (10:07 summary)'); }
function job_issuesEvening() { return T_issuesJob_('evening', 'TG group PLACE Team (23:10 summary)'); }
function T_issuesJob_(kind, channel) {
  return T_job_('issues', 'job_issues ' + kind, null, function () {
    var synced = T_syncIssuesFromQueue_();
    var t = ISS.issuesDigest_(kind);
    T_relay_('PLACE Team', channel, t);
    return {synced: synced, digest: t};
  });
}
/** Read-only copy of new «Тех вопросы» rows from the production queue (bridge log) into Issues of Place Inbox TEST.
 *  The live bridge is NOT changed. Queue rows have no reply link, so they only open issues (close in TEST by hand). */
function T_syncIssuesFromQueue_() {
  var p = PropertiesService.getScriptProperties(), key = 'T_ISS_QUEUE_ROW';
  var q = T_SS.openById(P_IDS.inbox).getSheetByName('queue'); if (!q) return 'no queue tab';
  var vals = q.getDataRange().getValues(), last = Number(p.getProperty(key) || Math.max(1, vals.length - 200)), n = 0;
  var sh = ISS.issuesSheet_();
  for (var r = last; r < vals.length; r++) {
    var row = vals[r], chat = String(row[1] || '');
    if (!ISS.ISSUES_CHAT_RE.test(chat) || !String(row[5] || '').trim()) continue;
    var d = row[0] instanceof Date ? row[0] : new Date();
    ISS.issuesHandle_(sh, {chat: {id: String(row[2] || 'queue'), title: chat}, message_id: 'q' + (r + 1), date: Math.floor(d.getTime() / 1000),
      from: {username: String(row[4] || '').replace(/^@/, '')}}, String(row[5]), String(row[3] || row[4] || '?'));
    n++;
  }
  p.setProperty(key, String(vals.length));
  return n + ' new from queue rows ' + (last + 1) + '..' + vals.length;
}
function job_timesheet() {
  return T_job_('timesheet', 'job_timesheet (prod Schedule 26 read-only)', function (to) {
    return {recipient: 'accountant (' + to + ')', channel: 'email draft to accountant'};
  }, function () { return ST5.createTimesheetDraft(); });
}
/** Every 3 days 20:00: remind the evening admin (shift ending 23:00) to prepare cash + count for the Thai partner. */
function job_cashReminder() {
  return T_job_('cash', 'job_cashReminder (prod Schedule 26 read-only)', null, function () {
    var now = new Date(), names = T_eveningAdmins_(now);
    var text = 'Cash for the bank / เงินสดฝากธนาคาร\n' +
      'Tomorrow the Thai partner collects the cash for the bank. After closing (23:00) please:\n' +
      '1) count the cash in the till;\n2) put it in the envelope with the count sheet (date, total, notes/coins, your name);\n' +
      '3) send the total + a photo of the count sheet here with #cash.\n\n' +
      'พรุ่งนี้พาร์ทเนอร์จะมารับเงินสดไปฝากธนาคาร หลังปิดร้าน (23:00) กรุณา:\n' +
      '1) นับเงินสดในลิ้นชัก\n2) ใส่ซองพร้อมใบนับเงิน (วันที่ ยอดรวม ธนบัตร/เหรียญ ชื่อผู้นับ)\n3) ส่งยอดรวม + รูปใบนับเงินที่นี่ พร้อม #cash';
    var who = names.length ? 'evening admin ' + names.join(', ') : 'evening admin (not found in Schedule 26 → Place Ops + George)';
    T_relay_(who, 'TG DM evening admin', text);
    return {eveningAdmins: names};
  });
}
function T_eveningAdmins_(d) {
  var c = SC.scCfg_(), sh = T_SS.openById(c.id).getSheetByName(c.tabs[d.getMonth()]);
  var m = SC.scReadTab_(sh, c); if (!m) return [];
  var day = Number(Utilities.formatDate(d, 'Asia/Bangkok', 'd'));
  return m.people.filter(function (p) { var s = SC.scShift_(p.days[day] || ''); return s && s.b >= 23; }).map(function (p) { return p.name; });
}

/** Dry check of all jobs right now (relay ON: George gets the messages if TG_TOKEN + GEORGE_CHAT_ID are set). */
function runAllJobsOnce() {
  var fns = {job_stage6: job_stage6, job_coverage: job_coverage, job_bookings: job_bookings, job_issuesMorning: job_issuesMorning,
    job_issuesEvening: job_issuesEvening, job_timesheet: job_timesheet, job_cashReminder: job_cashReminder};
  return T_JOBS.map(function (j) { return j[0] + ': ' + fns[j[0]]().status; });
}
